/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ConfidenceLevel_H_
#define	_ConfidenceLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfidenceLevel {
	ConfidenceLevel_unavailable	= 101
} e_ConfidenceLevel;

/* ConfidenceLevel */
typedef long	 ConfidenceLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ConfidenceLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ConfidenceLevel;
asn_struct_free_f ConfidenceLevel_free;
asn_struct_print_f ConfidenceLevel_print;
asn_constr_check_f ConfidenceLevel_constraint;
ber_type_decoder_f ConfidenceLevel_decode_ber;
der_type_encoder_f ConfidenceLevel_encode_der;
xer_type_decoder_f ConfidenceLevel_decode_xer;
xer_type_encoder_f ConfidenceLevel_encode_xer;
jer_type_encoder_f ConfidenceLevel_encode_jer;
oer_type_decoder_f ConfidenceLevel_decode_oer;
oer_type_encoder_f ConfidenceLevel_encode_oer;
per_type_decoder_f ConfidenceLevel_decode_uper;
per_type_encoder_f ConfidenceLevel_encode_uper;
per_type_decoder_f ConfidenceLevel_decode_aper;
per_type_encoder_f ConfidenceLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfidenceLevel_H_ */
#include "asn_internal.h"
