/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_LowerTriangularPositiveSemidefiniteMatrices_H_
#define	_LowerTriangularPositiveSemidefiniteMatrices_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LowerTriangularPositiveSemidefiniteMatrix;

/* LowerTriangularPositiveSemidefiniteMatrices */
typedef struct LowerTriangularPositiveSemidefiniteMatrices {
	A_SEQUENCE_OF(struct LowerTriangularPositiveSemidefiniteMatrix) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LowerTriangularPositiveSemidefiniteMatrices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LowerTriangularPositiveSemidefiniteMatrices;
extern asn_SET_OF_specifics_t asn_SPC_LowerTriangularPositiveSemidefiniteMatrices_specs_1;
extern asn_TYPE_member_t asn_MBR_LowerTriangularPositiveSemidefiniteMatrices_1[1];
extern asn_per_constraints_t asn_PER_type_LowerTriangularPositiveSemidefiniteMatrices_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LowerTriangularPositiveSemidefiniteMatrix.h"

#endif	/* _LowerTriangularPositiveSemidefiniteMatrices_H_ */
#include "asn_internal.h"
