/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_OccupiedLanesWithConfidence_H_
#define	_OccupiedLanesWithConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MetaInformation.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LanePositionOptions;
struct MapPosition;

/* OccupiedLanesWithConfidence */
typedef struct OccupiedLanesWithConfidence {
	struct OccupiedLanesWithConfidence__lanePositionBased {
		A_SEQUENCE_OF(struct LanePositionOptions) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lanePositionBased;
	struct OccupiedLanesWithConfidence__mapBased {
		A_SEQUENCE_OF(struct MapPosition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mapBased;
	MetaInformation_t	 confidence;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OccupiedLanesWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OccupiedLanesWithConfidence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LanePositionOptions.h"
#include "MapPosition.h"

#endif	/* _OccupiedLanesWithConfidence_H_ */
#include "asn_internal.h"
