/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PathId_H_
#define	_PathId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PathId {
	PathId_noPath	= 0,
	PathId_path1	= 1,
	PathId_path2	= 2,
	PathId_path3	= 3,
	PathId_path4	= 4,
	PathId_path5	= 5,
	PathId_path6	= 6,
	PathId_path7	= 7,
	PathId_pathExtended1	= 8,
	PathId_pathExtended2	= 9,
	PathId_pathExtended3	= 10,
	PathId_pathExtended4	= 11,
	PathId_pathExtended5	= 12,
	PathId_pathExtended6	= 13,
	PathId_pathExtended7	= 14
} e_PathId;

/* PathId */
typedef long	 PathId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PathId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PathId;
asn_struct_free_f PathId_free;
asn_struct_print_f PathId_print;
asn_constr_check_f PathId_constraint;
ber_type_decoder_f PathId_decode_ber;
der_type_encoder_f PathId_encode_der;
xer_type_decoder_f PathId_decode_xer;
xer_type_encoder_f PathId_encode_xer;
jer_type_encoder_f PathId_encode_jer;
oer_type_decoder_f PathId_decode_oer;
oer_type_encoder_f PathId_encode_oer;
per_type_decoder_f PathId_decode_uper;
per_type_encoder_f PathId_encode_uper;
per_type_decoder_f PathId_decode_aper;
per_type_encoder_f PathId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PathId_H_ */
#include "asn_internal.h"
