/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PerceptionRegionContainer"
 * 	found in "asn1/TS103324v211-CPM-PerceptionRegionContainer.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PerceptionRegion_H_
#define	_PerceptionRegion_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DeltaTimeMilliSecondSigned.h"
#include "ConfidenceLevel.h"
#include "Shape.h"
#include "BOOLEAN.h"
#include "CardinalNumber1B.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceOfIdentifier1B;
struct PerceivedObjectIds;

/* PerceptionRegion */
typedef struct PerceptionRegion {
	DeltaTimeMilliSecondSigned_t	 measurementDeltaTime;
	ConfidenceLevel_t	 perceptionRegionConfidence;
	Shape_t	 perceptionRegionShape;
	BOOLEAN_t	 shadowingApplies;
	struct SequenceOfIdentifier1B	*sensorIdList;	/* OPTIONAL */
	CardinalNumber1B_t	*numberOfPerceivedObjects;	/* OPTIONAL */
	struct PerceivedObjectIds	*perceivedObjectIds;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceptionRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceptionRegion;
extern asn_SEQUENCE_specifics_t asn_SPC_PerceptionRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceptionRegion_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SequenceOfIdentifier1B.h"
#include "PerceivedObjectIds.h"

#endif	/* _PerceptionRegion_H_ */
#include "asn_internal.h"
