/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_RadialShapeDetails_H_
#define	_RadialShapeDetails_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StandardLength12b.h"
#include "CartesianAngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RadialShapeDetails */
typedef struct RadialShapeDetails {
	StandardLength12b_t	 range;
	CartesianAngleValue_t	 horizontalOpeningAngleStart;
	CartesianAngleValue_t	 horizontalOpeningAngleEnd;
	CartesianAngleValue_t	*verticalOpeningAngleStart;	/* OPTIONAL */
	CartesianAngleValue_t	*verticalOpeningAngleEnd;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadialShapeDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadialShapeDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_RadialShapeDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_RadialShapeDetails_1[5];
extern asn_per_constraints_t asn_PER_type_RadialShapeDetails_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RadialShapeDetails_H_ */
#include "asn_internal.h"
