/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_StandardLength9b_H_
#define	_StandardLength9b_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StandardLength9b */
typedef long	 StandardLength9b_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_StandardLength9b_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_StandardLength9b;
asn_struct_free_f StandardLength9b_free;
asn_struct_print_f StandardLength9b_print;
asn_constr_check_f StandardLength9b_constraint;
ber_type_decoder_f StandardLength9b_decode_ber;
der_type_encoder_f StandardLength9b_encode_der;
xer_type_decoder_f StandardLength9b_decode_xer;
xer_type_encoder_f StandardLength9b_encode_xer;
jer_type_encoder_f StandardLength9b_encode_jer;
oer_type_decoder_f StandardLength9b_decode_oer;
oer_type_encoder_f StandardLength9b_encode_oer;
per_type_decoder_f StandardLength9b_decode_uper;
per_type_encoder_f StandardLength9b_encode_uper;
per_type_decoder_f StandardLength9b_decode_aper;
per_type_encoder_f StandardLength9b_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _StandardLength9b_H_ */
#include "asn_internal.h"
