/*
 * Generated by asn1c
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "TrustLists.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_CtlEntry_H_
#define	_Vanetza_Security2_CtlEntry_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RootCaEntry.h"
#include "EaEntry.h"
#include "AaEntry.h"
#include "DcEntry.h"
#include "TlmEntry.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security2_CtlEntry_PR {
	Vanetza_Security2_CtlEntry_PR_NOTHING,	/* No components present */
	Vanetza_Security2_CtlEntry_PR_rca,
	Vanetza_Security2_CtlEntry_PR_ea,
	Vanetza_Security2_CtlEntry_PR_aa,
	Vanetza_Security2_CtlEntry_PR_dc,
	Vanetza_Security2_CtlEntry_PR_tlm
	/* Extensions may appear below */
	
} Vanetza_Security2_CtlEntry_PR;

/* Vanetza_Security2_CtlEntry */
typedef struct Vanetza_Security2_CtlEntry {
	Vanetza_Security2_CtlEntry_PR present;
	union Vanetza_Security2_CtlEntry_u {
		Vanetza_Security2_RootCaEntry_t	 rca;
		Vanetza_Security2_EaEntry_t	 ea;
		Vanetza_Security2_AaEntry_t	 aa;
		Vanetza_Security2_DcEntry_t	 dc;
		Vanetza_Security2_TlmEntry_t	 tlm;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security2_CtlEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_CtlEntry;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_Security2_CtlEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security2_CtlEntry_1[5];
extern asn_oer_constraints_t asn_OER_type_Vanetza_Security2_CtlEntry_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_Security2_CtlEntry_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_CtlEntry_H_ */
#include "asn_internal.h"
