/*
 * Generated by asn1c
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "TS103097v211-Extension.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_EtsiTs102941CtlRequest_H_
#define	_Vanetza_Security2_EtsiTs102941CtlRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashedId8.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security2_EtsiTs102941CtlRequest */
typedef struct Vanetza_Security2_EtsiTs102941CtlRequest {
	Vanetza_Security2_HashedId8_t	 issuerId;
	long	*lastKnownCtlSequence;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security2_EtsiTs102941CtlRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_EtsiTs102941CtlRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security2_EtsiTs102941CtlRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security2_EtsiTs102941CtlRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_EtsiTs102941CtlRequest_H_ */
#include "asn_internal.h"
