/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_FullIeeeTbsCtl_H_
#define	_Vanetza_Security2_FullIeeeTbsCtl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609dot2dot1MsctlType.h"
#include "CtlSeriesId.h"
#include "CtlSequenceNumber.h"
#include "Time32.h"
#include "NativeInteger.h"
#include "CtlElectorEntry.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "CtlRootCaEntry.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security2_FullIeeeTbsCtl */
typedef struct Vanetza_Security2_FullIeeeTbsCtl {
	Vanetza_Security2_Ieee1609dot2dot1MsctlType_t	 type;
	Vanetza_Security2_CtlSeriesId_t	 ctlSeriesId;
	Vanetza_Security2_CtlSequenceNumber_t	 sequenceNumber;
	Vanetza_Security2_Time32_t	 effectiveDate;
	struct Vanetza_Security2_FullIeeeTbsCtl__electorApprove {
		A_SEQUENCE_OF(Vanetza_Security2_CtlElectorEntry_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} electorApprove;
	struct Vanetza_Security2_FullIeeeTbsCtl__electorRemove {
		A_SEQUENCE_OF(Vanetza_Security2_CtlElectorEntry_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} electorRemove;
	struct Vanetza_Security2_FullIeeeTbsCtl__rootCaApprove {
		A_SEQUENCE_OF(Vanetza_Security2_CtlRootCaEntry_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rootCaApprove;
	struct Vanetza_Security2_FullIeeeTbsCtl__rootCaRemove {
		A_SEQUENCE_OF(Vanetza_Security2_CtlRootCaEntry_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rootCaRemove;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*quorum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security2_FullIeeeTbsCtl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_FullIeeeTbsCtl;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security2_FullIeeeTbsCtl_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security2_FullIeeeTbsCtl_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_FullIeeeTbsCtl_H_ */
#include "asn_internal.h"
