/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_HashAlgorithm_H_
#define	_Vanetza_Security2_HashAlgorithm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security2_HashAlgorithm {
	Vanetza_Security2_HashAlgorithm_sha256	= 0,
	/*
	 * Enumeration is extensible
	 */
	Vanetza_Security2_HashAlgorithm_sha384	= 1,
	Vanetza_Security2_HashAlgorithm_sm3	= 2
} e_Vanetza_Security2_HashAlgorithm;

/* Vanetza_Security2_HashAlgorithm */
typedef long	 Vanetza_Security2_HashAlgorithm_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_Security2_HashAlgorithm_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_HashAlgorithm;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_Security2_HashAlgorithm_specs_1;
asn_struct_free_f Vanetza_Security2_HashAlgorithm_free;
asn_struct_print_f Vanetza_Security2_HashAlgorithm_print;
asn_constr_check_f Vanetza_Security2_HashAlgorithm_constraint;
ber_type_decoder_f Vanetza_Security2_HashAlgorithm_decode_ber;
der_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_der;
xer_type_decoder_f Vanetza_Security2_HashAlgorithm_decode_xer;
xer_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_xer;
jer_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_jer;
oer_type_decoder_f Vanetza_Security2_HashAlgorithm_decode_oer;
oer_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_oer;
per_type_decoder_f Vanetza_Security2_HashAlgorithm_decode_uper;
per_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_uper;
per_type_decoder_f Vanetza_Security2_HashAlgorithm_decode_aper;
per_type_encoder_f Vanetza_Security2_HashAlgorithm_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_HashAlgorithm_H_ */
#include "asn_internal.h"
