/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#include "LinkageData.h"

asn_TYPE_member_t asn_MBR_Vanetza_Security2_LinkageData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_Security2_LinkageData, iCert),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_Security2_IValue,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iCert"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_Security2_LinkageData, linkage_value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_Security2_LinkageValue,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"linkage-value"
		},
	{ ATF_POINTER, 1, offsetof(struct Vanetza_Security2_LinkageData, group_linkage_value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_Security2_GroupLinkageValue,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"group-linkage-value"
		},
};
static const int asn_MAP_Vanetza_Security2_LinkageData_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Vanetza_Security2_LinkageData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_Security2_LinkageData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iCert */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* linkage-value */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* group-linkage-value */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security2_LinkageData_specs_1 = {
	sizeof(struct Vanetza_Security2_LinkageData),
	offsetof(struct Vanetza_Security2_LinkageData, _asn_ctx),
	asn_MAP_Vanetza_Security2_LinkageData_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Vanetza_Security2_LinkageData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_LinkageData = {
	"LinkageData",
	"LinkageData",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_Security2_LinkageData_tags_1,
	sizeof(asn_DEF_Vanetza_Security2_LinkageData_tags_1)
		/sizeof(asn_DEF_Vanetza_Security2_LinkageData_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_Security2_LinkageData_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_Security2_LinkageData_tags_1)
		/sizeof(asn_DEF_Vanetza_Security2_LinkageData_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_Security2_LinkageData_1,
	3,	/* Elements count */
	&asn_SPC_Vanetza_Security2_LinkageData_specs_1	/* Additional specs */
};

