/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_SequenceOfPsidSsp_H_
#define	_Vanetza_Security2_SequenceOfPsidSsp_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_Security2_PsidSsp;

/* Vanetza_Security2_SequenceOfPsidSsp */
typedef struct Vanetza_Security2_SequenceOfPsidSsp {
	A_SEQUENCE_OF(struct Vanetza_Security2_PsidSsp) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security2_SequenceOfPsidSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_SequenceOfPsidSsp;
extern asn_SET_OF_specifics_t asn_SPC_Vanetza_Security2_SequenceOfPsidSsp_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security2_SequenceOfPsidSsp_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PsidSsp.h"

#endif	/* _Vanetza_Security2_SequenceOfPsidSsp_H_ */
#include "asn_internal.h"
