/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "build.asn1/ieee/IEEE1609dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_Uint64_H_
#define	_Vanetza_Security2_Uint64_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security2_Uint64 */
typedef INTEGER_t	 Vanetza_Security2_Uint64_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_Security2_Uint64_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_Uint64;
asn_struct_free_f Vanetza_Security2_Uint64_free;
asn_struct_print_f Vanetza_Security2_Uint64_print;
asn_constr_check_f Vanetza_Security2_Uint64_constraint;
ber_type_decoder_f Vanetza_Security2_Uint64_decode_ber;
der_type_encoder_f Vanetza_Security2_Uint64_encode_der;
xer_type_decoder_f Vanetza_Security2_Uint64_decode_xer;
xer_type_encoder_f Vanetza_Security2_Uint64_encode_xer;
jer_type_encoder_f Vanetza_Security2_Uint64_encode_jer;
oer_type_decoder_f Vanetza_Security2_Uint64_decode_oer;
oer_type_encoder_f Vanetza_Security2_Uint64_encode_oer;
per_type_decoder_f Vanetza_Security2_Uint64_decode_uper;
per_type_encoder_f Vanetza_Security2_Uint64_encode_uper;
per_type_decoder_f Vanetza_Security2_Uint64_decode_aper;
per_type_encoder_f Vanetza_Security2_Uint64_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_Uint64_H_ */
#include "asn_internal.h"
