/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security2_ -R`
 */

#ifndef	_Vanetza_Security2_ValidityPeriod_H_
#define	_Vanetza_Security2_ValidityPeriod_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Time32.h"
#include "Duration.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security2_ValidityPeriod */
typedef struct Vanetza_Security2_ValidityPeriod {
	Vanetza_Security2_Time32_t	 start;
	Vanetza_Security2_Duration_t	 duration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security2_ValidityPeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security2_ValidityPeriod;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security2_ValidityPeriod_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security2_ValidityPeriod_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security2_ValidityPeriod_H_ */
#include "asn_internal.h"
