/*
 * Generated by asn1c
 * From ASN.1 module "EtsiTs102941BaseTypes"
 * 	found in "TS102941v131-BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_CertificateSubjectAttributes_H_
#define	_Vanetza_Security_CertificateSubjectAttributes_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SubjectAssurance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_Security_CertificateId;
struct Vanetza_Security_ValidityPeriod;
struct Vanetza_Security_GeographicRegion;
struct Vanetza_Security_SequenceOfPsidSsp;
struct Vanetza_Security_SequenceOfPsidGroupPermissions;

/* Vanetza_Security_CertificateSubjectAttributes */
typedef struct Vanetza_Security_CertificateSubjectAttributes {
	struct Vanetza_Security_CertificateId	*id;	/* OPTIONAL */
	struct Vanetza_Security_ValidityPeriod	*validityPeriod;	/* OPTIONAL */
	struct Vanetza_Security_GeographicRegion	*region;	/* OPTIONAL */
	Vanetza_Security_SubjectAssurance_t	*assuranceLevel;	/* OPTIONAL */
	struct Vanetza_Security_SequenceOfPsidSsp	*appPermissions;	/* OPTIONAL */
	struct Vanetza_Security_SequenceOfPsidGroupPermissions	*certIssuePermissions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_CertificateSubjectAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_CertificateSubjectAttributes;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security_CertificateSubjectAttributes_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_CertificateSubjectAttributes_1[6];
extern asn_per_constraints_t asn_PER_type_Vanetza_Security_CertificateSubjectAttributes_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateId.h"
#include "ValidityPeriod.h"
#include "GeographicRegion.h"
#include "SequenceOfPsidSsp.h"
#include "SequenceOfPsidGroupPermissions.h"

#endif	/* _Vanetza_Security_CertificateSubjectAttributes_H_ */
#include "asn_internal.h"
