/*
 * Generated by asn1c
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "IEEE1609dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_EccP256CurvePoint_H_
#define	_Vanetza_Security_EccP256CurvePoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "NULL.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_EccP256CurvePoint_PR {
	Vanetza_Security_EccP256CurvePoint_PR_NOTHING,	/* No components present */
	Vanetza_Security_EccP256CurvePoint_PR_x_only,
	Vanetza_Security_EccP256CurvePoint_PR_fill,
	Vanetza_Security_EccP256CurvePoint_PR_compressed_y_0,
	Vanetza_Security_EccP256CurvePoint_PR_compressed_y_1,
	Vanetza_Security_EccP256CurvePoint_PR_uncompressedP256
} Vanetza_Security_EccP256CurvePoint_PR;

/* Vanetza_Security_EccP256CurvePoint */
typedef struct Vanetza_Security_EccP256CurvePoint {
	Vanetza_Security_EccP256CurvePoint_PR present;
	union Vanetza_Security_EccP256CurvePoint_u {
		OCTET_STRING_t	 x_only;
		NULL_t	 fill;
		OCTET_STRING_t	 compressed_y_0;
		OCTET_STRING_t	 compressed_y_1;
		struct Vanetza_Security_EccP256CurvePoint__uncompressedP256 {
			OCTET_STRING_t	 x;
			OCTET_STRING_t	 y;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} uncompressedP256;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_EccP256CurvePoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_EccP256CurvePoint;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_Security_EccP256CurvePoint_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_EccP256CurvePoint_1[5];
extern asn_oer_constraints_t asn_OER_type_Vanetza_Security_EccP256CurvePoint_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_Security_EccP256CurvePoint_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_EccP256CurvePoint_H_ */
#include "asn_internal.h"
