/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "asn1/IEEE1609dot2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_EncryptedData_H_
#define	_Vanetza_Security_EncryptedData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SequenceOfRecipientInfo.h"
#include "SymmetricCiphertext.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security_EncryptedData */
typedef struct Vanetza_Security_EncryptedData {
	Vanetza_Security_SequenceOfRecipientInfo_t	 recipients;
	Vanetza_Security_SymmetricCiphertext_t	 ciphertext;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_EncryptedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_EncryptedData;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security_EncryptedData_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_EncryptedData_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_EncryptedData_H_ */
#include "asn_internal.h"
