/*
 * Generated by asn1c
 * From ASN.1 module "EtsiTs102941TypesEnrolment"
 * 	found in "TS102941v131-TypesEnrolment.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_EnrolmentResponseCode_H_
#define	_Vanetza_Security_EnrolmentResponseCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_EnrolmentResponseCode {
	Vanetza_Security_EnrolmentResponseCode_ok	= 0,
	Vanetza_Security_EnrolmentResponseCode_cantparse	= 1,
	Vanetza_Security_EnrolmentResponseCode_badcontenttype	= 2,
	Vanetza_Security_EnrolmentResponseCode_imnottherecipient	= 3,
	Vanetza_Security_EnrolmentResponseCode_unknownencryptionalgorithm	= 4,
	Vanetza_Security_EnrolmentResponseCode_decryptionfailed	= 5,
	Vanetza_Security_EnrolmentResponseCode_unknownits	= 6,
	Vanetza_Security_EnrolmentResponseCode_invalidsignature	= 7,
	Vanetza_Security_EnrolmentResponseCode_invalidencryptionkey	= 8,
	Vanetza_Security_EnrolmentResponseCode_baditsstatus	= 9,
	Vanetza_Security_EnrolmentResponseCode_incompleterequest	= 10,
	Vanetza_Security_EnrolmentResponseCode_deniedpermissions	= 11,
	Vanetza_Security_EnrolmentResponseCode_invalidkeys	= 12,
	Vanetza_Security_EnrolmentResponseCode_deniedrequest	= 13
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_Security_EnrolmentResponseCode;

/* Vanetza_Security_EnrolmentResponseCode */
typedef long	 Vanetza_Security_EnrolmentResponseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_Security_EnrolmentResponseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_EnrolmentResponseCode;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_Security_EnrolmentResponseCode_specs_1;
asn_struct_free_f Vanetza_Security_EnrolmentResponseCode_free;
asn_struct_print_f Vanetza_Security_EnrolmentResponseCode_print;
asn_constr_check_f Vanetza_Security_EnrolmentResponseCode_constraint;
ber_type_decoder_f Vanetza_Security_EnrolmentResponseCode_decode_ber;
der_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_der;
xer_type_decoder_f Vanetza_Security_EnrolmentResponseCode_decode_xer;
xer_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_xer;
jer_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_jer;
oer_type_decoder_f Vanetza_Security_EnrolmentResponseCode_decode_oer;
oer_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_oer;
per_type_decoder_f Vanetza_Security_EnrolmentResponseCode_decode_uper;
per_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_uper;
per_type_decoder_f Vanetza_Security_EnrolmentResponseCode_decode_aper;
per_type_encoder_f Vanetza_Security_EnrolmentResponseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_EnrolmentResponseCode_H_ */
#include "asn_internal.h"
