/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "asn1/IEEE1609dot2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_HeaderInfo_H_
#define	_Vanetza_Security_HeaderInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Psid.h"
#include "Time64.h"
#include "HashedId3.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_Security_ThreeDLocation;
struct Vanetza_Security_MissingCrlIdentifier;
struct Vanetza_Security_EncryptionKey;
struct Vanetza_Security_SequenceOfHashedId3;
struct Vanetza_Security_Certificate;

/* Vanetza_Security_HeaderInfo */
typedef struct Vanetza_Security_HeaderInfo {
	Vanetza_Security_Psid_t	 psid;
	Vanetza_Security_Time64_t	*generationTime;	/* OPTIONAL */
	Vanetza_Security_Time64_t	*expiryTime;	/* OPTIONAL */
	struct Vanetza_Security_ThreeDLocation	*generationLocation;	/* OPTIONAL */
	Vanetza_Security_HashedId3_t	*p2pcdLearningRequest;	/* OPTIONAL */
	struct Vanetza_Security_MissingCrlIdentifier	*missingCrlIdentifier;	/* OPTIONAL */
	struct Vanetza_Security_EncryptionKey	*encryptionKey;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Vanetza_Security_SequenceOfHashedId3	*inlineP2pcdRequest;	/* OPTIONAL */
	struct Vanetza_Security_Certificate	*requestedCertificate;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_HeaderInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_HeaderInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security_HeaderInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_HeaderInfo_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ThreeDLocation.h"
#include "MissingCrlIdentifier.h"
#include "EncryptionKey.h"
#include "SequenceOfHashedId3.h"
#include "Certificate.h"

#endif	/* _Vanetza_Security_HeaderInfo_H_ */
#include "asn_internal.h"
