/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097Module"
 * 	found in "asn1/TS103097v131.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SingleEtsiTs103097Certificate_H_
#define	_SingleEtsiTs103097Certificate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs103097Certificate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SingleEtsiTs103097Certificate */
typedef struct SingleEtsiTs103097Certificate {
	EtsiTs103097Certificate_t	 only;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SingleEtsiTs103097Certificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SingleEtsiTs103097Certificate;

#ifdef __cplusplus
}
#endif

#endif	/* _SingleEtsiTs103097Certificate_H_ */
#include "asn_internal.h"
