/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "asn1/IEEE1609dot2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_CertificateType_H_
#define	_Vanetza_Security_CertificateType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_CertificateType {
	Vanetza_Security_CertificateType_explicit	= 0,
	Vanetza_Security_CertificateType_implicit	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_Security_CertificateType;

/* Vanetza_Security_CertificateType */
typedef long	 Vanetza_Security_CertificateType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_Security_CertificateType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_CertificateType;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_Security_CertificateType_specs_1;
asn_struct_free_f Vanetza_Security_CertificateType_free;
asn_struct_print_f Vanetza_Security_CertificateType_print;
asn_constr_check_f Vanetza_Security_CertificateType_constraint;
ber_type_decoder_f Vanetza_Security_CertificateType_decode_ber;
der_type_encoder_f Vanetza_Security_CertificateType_encode_der;
xer_type_decoder_f Vanetza_Security_CertificateType_decode_xer;
xer_type_encoder_f Vanetza_Security_CertificateType_encode_xer;
jer_type_encoder_f Vanetza_Security_CertificateType_encode_jer;
oer_type_decoder_f Vanetza_Security_CertificateType_decode_oer;
oer_type_encoder_f Vanetza_Security_CertificateType_encode_oer;
per_type_decoder_f Vanetza_Security_CertificateType_decode_uper;
per_type_encoder_f Vanetza_Security_CertificateType_encode_uper;
per_type_decoder_f Vanetza_Security_CertificateType_decode_aper;
per_type_encoder_f Vanetza_Security_CertificateType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_CertificateType_H_ */
#include "asn_internal.h"
