/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "build.asn1/iso/ISO14906-0-6.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ContractAuthenticator_H_
#define	_ContractAuthenticator_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ContractAuthenticator */
typedef OCTET_STRING_t	 ContractAuthenticator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContractAuthenticator;
asn_struct_free_f ContractAuthenticator_free;
asn_struct_print_f ContractAuthenticator_print;
asn_constr_check_f ContractAuthenticator_constraint;
ber_type_decoder_f ContractAuthenticator_decode_ber;
der_type_encoder_f ContractAuthenticator_encode_der;
xer_type_decoder_f ContractAuthenticator_decode_xer;
xer_type_encoder_f ContractAuthenticator_encode_xer;
jer_type_encoder_f ContractAuthenticator_encode_jer;
oer_type_decoder_f ContractAuthenticator_decode_oer;
oer_type_encoder_f ContractAuthenticator_encode_oer;
per_type_decoder_f ContractAuthenticator_decode_uper;
per_type_encoder_f ContractAuthenticator_encode_uper;
per_type_decoder_f ContractAuthenticator_decode_aper;
per_type_encoder_f ContractAuthenticator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ContractAuthenticator_H_ */
#include "asn_internal.h"
