/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "build.asn1/iso/ISO14823.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DistanceOrDuration_H_
#define	_DistanceOrDuration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "Code-Units.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DistanceOrDuration */
typedef struct DistanceOrDuration {
	long	 value;
	Code_Units_t	 unit;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DistanceOrDuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistanceOrDuration;
extern asn_SEQUENCE_specifics_t asn_SPC_DistanceOrDuration_specs_1;
extern asn_TYPE_member_t asn_MBR_DistanceOrDuration_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DistanceOrDuration_H_ */
#include "asn_internal.h"
