/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "build.asn1/iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SaeAutomationLevel_H_
#define	_SaeAutomationLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SaeAutomationLevel */
typedef long	 SaeAutomationLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SaeAutomationLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SaeAutomationLevel;
asn_struct_free_f SaeAutomationLevel_free;
asn_struct_print_f SaeAutomationLevel_print;
asn_constr_check_f SaeAutomationLevel_constraint;
ber_type_decoder_f SaeAutomationLevel_decode_ber;
der_type_encoder_f SaeAutomationLevel_encode_der;
xer_type_decoder_f SaeAutomationLevel_decode_xer;
xer_type_encoder_f SaeAutomationLevel_encode_xer;
jer_type_encoder_f SaeAutomationLevel_encode_jer;
oer_type_decoder_f SaeAutomationLevel_decode_oer;
oer_type_encoder_f SaeAutomationLevel_encode_oer;
per_type_decoder_f SaeAutomationLevel_decode_uper;
per_type_encoder_f SaeAutomationLevel_encode_uper;
per_type_decoder_f SaeAutomationLevel_decode_aper;
per_type_encoder_f SaeAutomationLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SaeAutomationLevel_H_ */
#include "asn_internal.h"
