/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_StationDataContainer_H_
#define	_StationDataContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OriginatingVehicleContainer.h"
#include "OriginatingRSUContainer.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StationDataContainer_PR {
	StationDataContainer_PR_NOTHING,	/* No components present */
	StationDataContainer_PR_originatingVehicleContainer,
	StationDataContainer_PR_originatingRSUContainer
	/* Extensions may appear below */
	
} StationDataContainer_PR;

/* StationDataContainer */
typedef struct StationDataContainer {
	StationDataContainer_PR present;
	union StationDataContainer_u {
		OriginatingVehicleContainer_t	 originatingVehicleContainer;
		OriginatingRSUContainer_t	 originatingRSUContainer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationDataContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationDataContainer;
extern asn_CHOICE_specifics_t asn_SPC_StationDataContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_StationDataContainer_1[2];
extern asn_per_constraints_t asn_PER_type_StationDataContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _StationDataContainer_H_ */
#include "asn_internal.h"
