/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleSensorPropertyList_H_
#define	_VehicleSensorPropertyList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSensorProperties;

/* VehicleSensorPropertyList */
typedef struct VehicleSensorPropertyList {
	A_SEQUENCE_OF(struct VehicleSensorProperties) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSensorPropertyList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSensorPropertyList;
extern asn_SET_OF_specifics_t asn_SPC_VehicleSensorPropertyList_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSensorPropertyList_1[1];
extern asn_per_constraints_t asn_PER_type_VehicleSensorPropertyList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleSensorProperties.h"

#endif	/* _VehicleSensorPropertyList_H_ */
#include "asn_internal.h"
