/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "asn1/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_HeadingConfidenceDSRC_H_
#define	_HeadingConfidenceDSRC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HeadingConfidenceDSRC {
	HeadingConfidenceDSRC_unavailable	= 0,
	HeadingConfidenceDSRC_prec10deg	= 1,
	HeadingConfidenceDSRC_prec05deg	= 2,
	HeadingConfidenceDSRC_prec01deg	= 3,
	HeadingConfidenceDSRC_prec0_1deg	= 4,
	HeadingConfidenceDSRC_prec0_05deg	= 5,
	HeadingConfidenceDSRC_prec0_01deg	= 6,
	HeadingConfidenceDSRC_prec0_0125deg	= 7
} e_HeadingConfidenceDSRC;

/* HeadingConfidenceDSRC */
typedef long	 HeadingConfidenceDSRC_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HeadingConfidenceDSRC_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HeadingConfidenceDSRC;
extern const asn_INTEGER_specifics_t asn_SPC_HeadingConfidenceDSRC_specs_1;
asn_struct_free_f HeadingConfidenceDSRC_free;
asn_struct_print_f HeadingConfidenceDSRC_print;
asn_constr_check_f HeadingConfidenceDSRC_constraint;
ber_type_decoder_f HeadingConfidenceDSRC_decode_ber;
der_type_encoder_f HeadingConfidenceDSRC_encode_der;
xer_type_decoder_f HeadingConfidenceDSRC_decode_xer;
xer_type_encoder_f HeadingConfidenceDSRC_encode_xer;
oer_type_decoder_f HeadingConfidenceDSRC_decode_oer;
oer_type_encoder_f HeadingConfidenceDSRC_encode_oer;
per_type_decoder_f HeadingConfidenceDSRC_decode_uper;
per_type_encoder_f HeadingConfidenceDSRC_encode_uper;
per_type_decoder_f HeadingConfidenceDSRC_decode_aper;
per_type_encoder_f HeadingConfidenceDSRC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HeadingConfidenceDSRC_H_ */
#include "asn_internal.h"
