/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "build.asn1/iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_LaneInformation_H_
#define	_LaneInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LanePosition.h"
#include "Direction.h"
#include "LaneType.h"
#include "LaneStatus.h"
#include "IviLaneWidth.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InternationalSign_applicablePeriod;
struct CompleteVehicleCharacteristics;
struct ZoneIds;
struct LaneCharacteristics;
struct RoadSurfaceStaticCharacteristics;
struct RoadSurfaceDynamicCharacteristics;

/* LaneInformation */
typedef struct LaneInformation {
	LanePosition_t	 laneNumber;
	Direction_t	 direction;
	struct InternationalSign_applicablePeriod	*validity;	/* OPTIONAL */
	LaneType_t	 laneType;
	struct CompleteVehicleCharacteristics	*laneTypeQualifier;	/* OPTIONAL */
	LaneStatus_t	 laneStatus;
	IviLaneWidth_t	*laneWidth;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LaneInformation__ext1 {
		struct ZoneIds	*detectionZoneIds;	/* OPTIONAL */
		struct ZoneIds	*relevanceZoneIds;	/* OPTIONAL */
		struct LaneCharacteristics	*laneCharacteristics;	/* OPTIONAL */
		struct RoadSurfaceStaticCharacteristics	*laneSurfaceStaticCharacteristics;	/* OPTIONAL */
		struct RoadSurfaceDynamicCharacteristics	*laneSurfaceDynamicCharacteristics;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_LaneInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_LaneInformation_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InternationalSign-applicablePeriod.h"
#include "CompleteVehicleCharacteristics.h"
#include "ZoneIds.h"
#include "LaneCharacteristics.h"
#include "RoadSurfaceStaticCharacteristics.h"
#include "RoadSurfaceDynamicCharacteristics.h"

#endif	/* _LaneInformation_H_ */
#include "asn_internal.h"
