/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "REG-D"
 * 	found in "asn1/MAP_SPAT_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Reg_RestrictionUserType_H_
#define	_Reg_RestrictionUserType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EmissionType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Reg-RestrictionUserType */
typedef struct Reg_RestrictionUserType {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Reg_RestrictionUserType__ext1 {
		EmissionType_t	*emission;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reg_RestrictionUserType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reg_RestrictionUserType;
extern asn_SEQUENCE_specifics_t asn_SPC_Reg_RestrictionUserType_specs_1;
extern asn_TYPE_member_t asn_MBR_Reg_RestrictionUserType_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Reg_RestrictionUserType_H_ */
#include "asn_internal.h"
