/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "REGION"
 * 	found in "asn1/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Reg_MovementEvent_H_
#define	_Reg_MovementEvent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Reg-MovementEvent */
typedef struct Reg_MovementEvent {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reg_MovementEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reg_MovementEvent;
extern asn_SEQUENCE_specifics_t asn_SPC_Reg_MovementEvent_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Reg_MovementEvent_H_ */
#include "asn_internal.h"
