/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "asn1/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_RegionalNodeAttributeList_H_
#define	_RegionalNodeAttributeList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionalNodeAttribute;

/* RegionalNodeAttributeList */
typedef struct RegionalNodeAttributeList {
	A_SEQUENCE_OF(struct RegionalNodeAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalNodeAttributeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalNodeAttributeList;
extern asn_SET_OF_specifics_t asn_SPC_RegionalNodeAttributeList_specs_1;
extern asn_TYPE_member_t asn_MBR_RegionalNodeAttributeList_1[1];
extern asn_per_constraints_t asn_PER_type_RegionalNodeAttributeList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RegionalNodeAttribute.h"

#endif	/* _RegionalNodeAttributeList_H_ */
#include "asn_internal.h"
