/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "asn1/DSRC_REG_D.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SegmentAttribute_H_
#define	_SegmentAttribute_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SegmentAttribute {
	SegmentAttribute_reserved	= 0,
	SegmentAttribute_doNotBlock	= 1,
	SegmentAttribute_whiteLine	= 2,
	SegmentAttribute_mergingLaneLeft	= 3,
	SegmentAttribute_mergingLaneRight	= 4,
	SegmentAttribute_curbOnLeft	= 5,
	SegmentAttribute_curbOnRight	= 6,
	SegmentAttribute_loadingzoneOnLeft	= 7,
	SegmentAttribute_loadingzoneOnRight	= 8,
	SegmentAttribute_turnOutPointOnLeft	= 9,
	SegmentAttribute_turnOutPointOnRight	= 10,
	SegmentAttribute_adjacentParkingOnLeft	= 11,
	SegmentAttribute_adjacentParkingOnRight	= 12,
	SegmentAttribute_adjacentBikeLaneOnLeft	= 13,
	SegmentAttribute_adjacentBikeLaneOnRight	= 14,
	SegmentAttribute_sharedBikeLane	= 15,
	SegmentAttribute_bikeBoxInFront	= 16,
	SegmentAttribute_transitStopOnLeft	= 17,
	SegmentAttribute_transitStopOnRight	= 18,
	SegmentAttribute_transitStopInLane	= 19,
	SegmentAttribute_sharedWithTrackedVehicle	= 20,
	SegmentAttribute_safeIsland	= 21,
	SegmentAttribute_lowCurbsPresent	= 22,
	SegmentAttribute_rumbleStripPresent	= 23,
	SegmentAttribute_audibleSignalingPresent	= 24,
	SegmentAttribute_adaptiveTimingPresent	= 25,
	SegmentAttribute_rfSignalRequestPresent	= 26,
	SegmentAttribute_partialCurbIntrusion	= 27,
	SegmentAttribute_taperToLeft	= 28,
	SegmentAttribute_taperToRight	= 29,
	SegmentAttribute_taperToCenterLine	= 30,
	SegmentAttribute_parallelParking	= 31,
	SegmentAttribute_headInParking	= 32,
	SegmentAttribute_freeParking	= 33,
	SegmentAttribute_timeRestrictionsOnParking	= 34,
	SegmentAttribute_costToPark	= 35,
	SegmentAttribute_midBlockCurbPresent	= 36,
	SegmentAttribute_unEvenPavementPresent	= 37
	/*
	 * Enumeration is extensible
	 */
} e_SegmentAttribute;

/* SegmentAttribute */
typedef long	 SegmentAttribute_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SegmentAttribute_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SegmentAttribute;
extern const asn_INTEGER_specifics_t asn_SPC_SegmentAttribute_specs_1;
asn_struct_free_f SegmentAttribute_free;
asn_struct_print_f SegmentAttribute_print;
asn_constr_check_f SegmentAttribute_constraint;
ber_type_decoder_f SegmentAttribute_decode_ber;
der_type_encoder_f SegmentAttribute_encode_der;
xer_type_decoder_f SegmentAttribute_decode_xer;
xer_type_encoder_f SegmentAttribute_encode_xer;
oer_type_decoder_f SegmentAttribute_decode_oer;
oer_type_encoder_f SegmentAttribute_encode_oer;
per_type_decoder_f SegmentAttribute_decode_uper;
per_type_encoder_f SegmentAttribute_encode_uper;
per_type_decoder_f SegmentAttribute_decode_aper;
per_type_encoder_f SegmentAttribute_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SegmentAttribute_H_ */
#include "asn_internal.h"
