/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "build.asn1/iso/ISO19091.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SignalRequestMessage_H_
#define	_SignalRequestMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "MsgCount.h"
#include "RequestorDescription.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalRequestList;
struct Reg_SignalRequestMessage;

/* SignalRequestMessage */
typedef struct SignalRequestMessage {
	MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	DSecond_t	 second;
	MsgCount_t	*sequenceNumber;	/* OPTIONAL */
	struct SignalRequestList	*requests;	/* OPTIONAL */
	RequestorDescription_t	 requestor;
	struct SignalRequestMessage__regional {
		A_SEQUENCE_OF(struct Reg_SignalRequestMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalRequestList.h"
#include "RegionalExtension.h"

#endif	/* _SignalRequestMessage_H_ */
#include "asn_internal.h"
