/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "build.asn1/iso/ISO14906-0-6.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TrailerAxles_H_
#define	_TrailerAxles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TrailerAxles */
typedef long	 TrailerAxles_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TrailerAxles_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TrailerAxles;
asn_struct_free_f TrailerAxles_free;
asn_struct_print_f TrailerAxles_print;
asn_constr_check_f TrailerAxles_constraint;
ber_type_decoder_f TrailerAxles_decode_ber;
der_type_encoder_f TrailerAxles_encode_der;
xer_type_decoder_f TrailerAxles_decode_xer;
xer_type_encoder_f TrailerAxles_encode_xer;
jer_type_encoder_f TrailerAxles_encode_jer;
oer_type_decoder_f TrailerAxles_decode_oer;
oer_type_encoder_f TrailerAxles_encode_oer;
per_type_decoder_f TrailerAxles_decode_uper;
per_type_encoder_f TrailerAxles_encode_uper;
per_type_decoder_f TrailerAxles_decode_aper;
per_type_encoder_f TrailerAxles_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrailerAxles_H_ */
#include "asn_internal.h"
