/*
 * Generated by asn1c
 * From ASN.1 module "IVI"
 * 	found in "ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleCharacteristicsList_H_
#define	_VehicleCharacteristicsList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CompleteVehicleCharacteristics;

/* VehicleCharacteristicsList */
typedef struct VehicleCharacteristicsList {
	A_SEQUENCE_OF(struct CompleteVehicleCharacteristics) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleCharacteristicsList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleCharacteristicsList;
extern asn_SET_OF_specifics_t asn_SPC_VehicleCharacteristicsList_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleCharacteristicsList_1[1];
extern asn_oer_constraints_t asn_OER_type_VehicleCharacteristicsList_constr_1;
extern asn_per_constraints_t asn_PER_type_VehicleCharacteristicsList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CompleteVehicleCharacteristics.h"

#endif	/* _VehicleCharacteristicsList_H_ */
#include "asn_internal.h"
