/*
 * Generated by asn1c
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "TS103900v231-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_CAM_H_
#define	_Vanetza_ITS2_CAM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "CamPayload.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_CAM */
typedef struct Vanetza_ITS2_CAM {
	Vanetza_ITS2_ItsPduHeader_t	 header;
	Vanetza_ITS2_CamPayload_t	 cam;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_CAM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_CAM;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_CAM_H_ */
#include "asn_internal.h"
