/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/release2/TS103324v211/CPM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#include "ConstraintWrappedCpmContainers.h"

int
Vanetza_ITS2_ConstraintWrappedCpmContainers_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 8UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using Vanetza_ITS2_WrappedCpmContainers,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_ConstraintWrappedCpmContainers_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..8)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ConstraintWrappedCpmContainers_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers = {
	"ConstraintWrappedCpmContainers",
	"ConstraintWrappedCpmContainers",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_ConstraintWrappedCpmContainers_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_ConstraintWrappedCpmContainers_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_ConstraintWrappedCpmContainers_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		Vanetza_ITS2_ConstraintWrappedCpmContainers_constraint
	},
	asn_MBR_Vanetza_ITS2_WrappedCpmContainers_1,
	1,	/* Single element */
	&asn_SPC_Vanetza_ITS2_WrappedCpmContainers_specs_1	/* Additional specs */
};

