/*
 * Generated by asn1c
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "TS103831v221-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_DenmPayload_H_
#define	_Vanetza_ITS2_DenmPayload_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DENM-PDU-Description_ManagementContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_SituationContainer;
struct Vanetza_ITS2_LocationContainer;
struct Vanetza_ITS2_AlacarteContainer;

/* Vanetza_ITS2_DenmPayload */
typedef struct Vanetza_ITS2_DenmPayload {
	Vanetza_ITS2_DENM_PDU_Description_ManagementContainer_t	 management;
	struct Vanetza_ITS2_SituationContainer	*situation;	/* OPTIONAL */
	struct Vanetza_ITS2_LocationContainer	*location;	/* OPTIONAL */
	struct Vanetza_ITS2_AlacarteContainer	*alacarte;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_DenmPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_DenmPayload;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_DenmPayload_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_DenmPayload_1[4];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_DenmPayload_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_DenmPayload_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SituationContainer.h"
#include "LocationContainer.h"
#include "AlacarteContainer.h"

#endif	/* _Vanetza_ITS2_DenmPayload_H_ */
#include "asn_internal.h"
