/*
 * Generated by asn1c
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "TS103900v231-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_EHorizonLocationSharingContainer_H_
#define	_Vanetza_ITS2_EHorizonLocationSharingContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PolygonalLine.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_ConfidenceLevels;
struct Vanetza_ITS2_BasicLaneConfiguration;
struct Vanetza_ITS2_MetaInformation;

/* Vanetza_ITS2_EHorizonLocationSharingContainer */
typedef struct Vanetza_ITS2_EHorizonLocationSharingContainer {
	Vanetza_ITS2_PolygonalLine_t	 segmentAhead;
	struct Vanetza_ITS2_ConfidenceLevels	*nodeProbabilities;	/* OPTIONAL */
	Vanetza_ITS2_PolygonalLine_t	 segmentBehind;
	struct Vanetza_ITS2_BasicLaneConfiguration	*laneLevelDetails;	/* OPTIONAL */
	struct Vanetza_ITS2_MetaInformation	*segmentSource;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_EHorizonLocationSharingContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_EHorizonLocationSharingContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_EHorizonLocationSharingContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_EHorizonLocationSharingContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfidenceLevels.h"
#include "BasicLaneConfiguration.h"
#include "MetaInformation.h"

#endif	/* _Vanetza_ITS2_EHorizonLocationSharingContainer_H_ */
#include "asn_internal.h"
