/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v241-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_EllipticalShape_H_
#define	_Vanetza_ITS2_EllipticalShape_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StandardLength12b.h"
#include "CartesianAngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_CartesianPosition3d;

/* Vanetza_ITS2_EllipticalShape */
typedef struct Vanetza_ITS2_EllipticalShape {
	struct Vanetza_ITS2_CartesianPosition3d	*shapeReferencePoint;	/* OPTIONAL */
	Vanetza_ITS2_StandardLength12b_t	 semiMajorAxisLength;
	Vanetza_ITS2_StandardLength12b_t	 semiMinorAxisLength;
	Vanetza_ITS2_CartesianAngleValue_t	*orientation;	/* OPTIONAL */
	Vanetza_ITS2_StandardLength12b_t	*height;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_EllipticalShape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_EllipticalShape;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_EllipticalShape_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_EllipticalShape_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CartesianPosition3d.h"

#endif	/* _Vanetza_ITS2_EllipticalShape_H_ */
#include "asn_internal.h"
