/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_Ext1_H_
#define	_Vanetza_ITS2_Ext1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "Ext2.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_Ext1_PR {
	Vanetza_ITS2_Ext1_PR_NOTHING,	/* No components present */
	Vanetza_ITS2_Ext1_PR_content,
	Vanetza_ITS2_Ext1_PR_extension
} Vanetza_ITS2_Ext1_PR;

/* Vanetza_ITS2_Ext1 */
typedef struct Vanetza_ITS2_Ext1 {
	Vanetza_ITS2_Ext1_PR present;
	union Vanetza_ITS2_Ext1_u {
		long	 content;
		Vanetza_ITS2_Ext2_t	 extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_Ext1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_Ext1;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_Ext1_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_Ext1_1[2];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_Ext1_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_Ext1_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_Ext1_H_ */
#include "asn_internal.h"
