/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_HeadingValue_H_
#define	_Vanetza_ITS2_HeadingValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_HeadingValue {
	Vanetza_ITS2_HeadingValue_wgs84North	= 0,
	Vanetza_ITS2_HeadingValue_wgs84East	= 900,
	Vanetza_ITS2_HeadingValue_wgs84South	= 1800,
	Vanetza_ITS2_HeadingValue_wgs84West	= 2700,
	Vanetza_ITS2_HeadingValue_doNotUse	= 3600,
	Vanetza_ITS2_HeadingValue_unavailable	= 3601
} e_Vanetza_ITS2_HeadingValue;

/* Vanetza_ITS2_HeadingValue */
typedef long	 Vanetza_ITS2_HeadingValue_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_HeadingValue_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_HeadingValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_HeadingValue;
asn_struct_free_f Vanetza_ITS2_HeadingValue_free;
asn_struct_print_f Vanetza_ITS2_HeadingValue_print;
asn_constr_check_f Vanetza_ITS2_HeadingValue_constraint;
ber_type_decoder_f Vanetza_ITS2_HeadingValue_decode_ber;
der_type_encoder_f Vanetza_ITS2_HeadingValue_encode_der;
xer_type_decoder_f Vanetza_ITS2_HeadingValue_decode_xer;
xer_type_encoder_f Vanetza_ITS2_HeadingValue_encode_xer;
jer_type_encoder_f Vanetza_ITS2_HeadingValue_encode_jer;
oer_type_decoder_f Vanetza_ITS2_HeadingValue_decode_oer;
oer_type_encoder_f Vanetza_ITS2_HeadingValue_encode_oer;
per_type_decoder_f Vanetza_ITS2_HeadingValue_decode_uper;
per_type_encoder_f Vanetza_ITS2_HeadingValue_encode_uper;
per_type_decoder_f Vanetza_ITS2_HeadingValue_decode_aper;
per_type_encoder_f Vanetza_ITS2_HeadingValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_HeadingValue_H_ */
#include "asn_internal.h"
