/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v241-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_IssuerIdentifier_H_
#define	_Vanetza_ITS2_IssuerIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_IssuerIdentifier */
typedef long	 Vanetza_ITS2_IssuerIdentifier_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_IssuerIdentifier_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_IssuerIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_IssuerIdentifier;
asn_struct_free_f Vanetza_ITS2_IssuerIdentifier_free;
asn_struct_print_f Vanetza_ITS2_IssuerIdentifier_print;
asn_constr_check_f Vanetza_ITS2_IssuerIdentifier_constraint;
ber_type_decoder_f Vanetza_ITS2_IssuerIdentifier_decode_ber;
der_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_der;
xer_type_decoder_f Vanetza_ITS2_IssuerIdentifier_decode_xer;
xer_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_xer;
jer_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_jer;
oer_type_decoder_f Vanetza_ITS2_IssuerIdentifier_decode_oer;
oer_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_oer;
per_type_decoder_f Vanetza_ITS2_IssuerIdentifier_decode_uper;
per_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_uper;
per_type_decoder_f Vanetza_ITS2_IssuerIdentifier_decode_aper;
per_type_encoder_f Vanetza_ITS2_IssuerIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_IssuerIdentifier_H_ */
#include "asn_internal.h"
