/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-OriginatingStationContainers"
 * 	found in "asn1/release2/TS103324v211/CPM-OriginatingStationContainers.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_OriginatingVehicleContainer_H_
#define	_Vanetza_ITS2_OriginatingVehicleContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Wgs84Angle.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_CartesianAngle;
struct Vanetza_ITS2_TrailerDataSet;

/* Vanetza_ITS2_OriginatingVehicleContainer */
typedef struct Vanetza_ITS2_OriginatingVehicleContainer {
	Vanetza_ITS2_Wgs84Angle_t	 orientationAngle;
	struct Vanetza_ITS2_CartesianAngle	*pitchAngle;	/* OPTIONAL */
	struct Vanetza_ITS2_CartesianAngle	*rollAngle;	/* OPTIONAL */
	struct Vanetza_ITS2_TrailerDataSet	*trailerDataSet;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_OriginatingVehicleContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_OriginatingVehicleContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_OriginatingVehicleContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_OriginatingVehicleContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CartesianAngle.h"
#include "TrailerDataSet.h"

#endif	/* _Vanetza_ITS2_OriginatingVehicleContainer_H_ */
#include "asn_internal.h"
