/*
 * Generated by asn1c
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "POIM-ParkingAvailability.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ParkingArea_H_
#define	_Vanetza_ITS2_ParkingArea_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier2B.h"
#include "OccupancyInformation.h"
#include "GeoPosition.h"
#include "NativeInteger.h"
#include "ParkingAreaArrangementType.h"
#include "VehicleHeight.h"
#include "UTF8String.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "EngineCharacteristicsFromIso.h"
#include "ParkingReservationType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_DeltaPositions;
struct Vanetza_ITS2_Wgs84Angle;
struct Vanetza_ITS2_ParkingSpacesBasic;
struct Vanetza_ITS2_ParkingSpacesDetailed;
struct Vanetza_ITS2_EuVehicleCategoryCode;
struct Vanetza_ITS2_LoadType;
struct Vanetza_ITS2_DeltaPosition;

/* Vanetza_ITS2_ParkingArea */
typedef struct Vanetza_ITS2_ParkingArea {
	Vanetza_ITS2_Identifier2B_t	 id;
	Vanetza_ITS2_OccupancyInformation_t	 currentOccupancy;
	Vanetza_ITS2_GeoPosition_t	 location;
	long	 level;	/* DEFAULT 0 */
	Vanetza_ITS2_ParkingAreaArrangementType_t	 arrangementType;
	struct Vanetza_ITS2_DeltaPositions	*boundary;	/* OPTIONAL */
	struct Vanetza_ITS2_Wgs84Angle	*orientation;	/* OPTIONAL */
	Vanetza_ITS2_Identifier2B_t	*accessViaLane;	/* OPTIONAL */
	struct Vanetza_ITS2_ParkingArea__allowedVehicleCategories {
		A_SEQUENCE_OF(struct Vanetza_ITS2_EuVehicleCategoryCode) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} allowedVehicleCategories;
	struct Vanetza_ITS2_ParkingArea__notAllowedEngineCharacteristics {
		A_SEQUENCE_OF(Vanetza_ITS2_EngineCharacteristicsFromIso_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *notAllowedEngineCharacteristics;
	struct Vanetza_ITS2_ParkingArea__allowedLoadTypes {
		A_SEQUENCE_OF(struct Vanetza_ITS2_LoadType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *allowedLoadTypes;
	struct Vanetza_ITS2_ParkingArea__notAllowedLoadTypes {
		A_SEQUENCE_OF(struct Vanetza_ITS2_LoadType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *notAllowedLoadTypes;
	Vanetza_ITS2_VehicleHeight_t	*heightRestriction;	/* OPTIONAL */
	struct Vanetza_ITS2_ParkingArea__reservationType {
		A_SEQUENCE_OF(Vanetza_ITS2_ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationType;
	UTF8String_t	*pricingInformation;	/* OPTIONAL */
	UTF8String_t	*paymentInformation;	/* OPTIONAL */
	UTF8String_t	*bookingContactInfo;	/* OPTIONAL */
	UTF8String_t	*accessCharachteristics;	/* OPTIONAL */
	struct Vanetza_ITS2_ParkingArea__freeSpacesPosition {
		A_SEQUENCE_OF(struct Vanetza_ITS2_DeltaPosition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *freeSpacesPosition;
	struct Vanetza_ITS2_ParkingArea__freeSpacesId {
		A_SEQUENCE_OF(Vanetza_ITS2_Identifier2B_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *freeSpacesId;
	struct Vanetza_ITS2_ParkingSpacesBasic	*spacesBasic;	/* OPTIONAL */
	struct Vanetza_ITS2_ParkingSpacesDetailed	*spacesDetailed;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ParkingArea_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ParkingArea;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_ParkingArea_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ParkingArea_1[22];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DeltaPositions.h"
#include "Wgs84Angle.h"
#include "ParkingSpacesBasic.h"
#include "ParkingSpacesDetailed.h"
#include "EuVehicleCategoryCode.h"
#include "LoadType.h"
#include "DeltaPosition.h"

#endif	/* _Vanetza_ITS2_ParkingArea_H_ */
#include "asn_internal.h"
