/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "asn1/release2/TS103916v211/POIM-ParkingAvailability.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ParkingReservationType_H_
#define	_Vanetza_ITS2_ParkingReservationType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_ParkingReservationType {
	Vanetza_ITS2_ParkingReservationType_disabled	= 0,
	Vanetza_ITS2_ParkingReservationType_pregnant	= 1,
	Vanetza_ITS2_ParkingReservationType_womenOnly	= 2,
	Vanetza_ITS2_ParkingReservationType_parentAndChild	= 3,
	Vanetza_ITS2_ParkingReservationType_loadAndOffloadGoods	= 4,
	Vanetza_ITS2_ParkingReservationType_manualElectricVehicleCharging	= 5,
	Vanetza_ITS2_ParkingReservationType_automatedElectricVehicleCharging	= 6,
	Vanetza_ITS2_ParkingReservationType_refriferatedTransport	= 7,
	Vanetza_ITS2_ParkingReservationType_vip	= 8,
	Vanetza_ITS2_ParkingReservationType_preBooking	= 9,
	Vanetza_ITS2_ParkingReservationType_freeToBeReserved	= 10,
	Vanetza_ITS2_ParkingReservationType_reservationNotPossible	= 11,
	Vanetza_ITS2_ParkingReservationType_automatedValetparking	= 12,
	Vanetza_ITS2_ParkingReservationType_permit	= 13
} e_Vanetza_ITS2_ParkingReservationType;

/* Vanetza_ITS2_ParkingReservationType */
typedef long	 Vanetza_ITS2_ParkingReservationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ParkingReservationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ParkingReservationType;
asn_struct_free_f Vanetza_ITS2_ParkingReservationType_free;
asn_struct_print_f Vanetza_ITS2_ParkingReservationType_print;
asn_constr_check_f Vanetza_ITS2_ParkingReservationType_constraint;
ber_type_decoder_f Vanetza_ITS2_ParkingReservationType_decode_ber;
der_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_der;
xer_type_decoder_f Vanetza_ITS2_ParkingReservationType_decode_xer;
xer_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_xer;
jer_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_jer;
oer_type_decoder_f Vanetza_ITS2_ParkingReservationType_decode_oer;
oer_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_oer;
per_type_decoder_f Vanetza_ITS2_ParkingReservationType_decode_uper;
per_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_uper;
per_type_decoder_f Vanetza_ITS2_ParkingReservationType_decode_aper;
per_type_encoder_f Vanetza_ITS2_ParkingReservationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_ParkingReservationType_H_ */
#include "asn_internal.h"
