/*
 * Generated by asn1c
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "POIM-ParkingAvailability.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ParkingStatus_H_
#define	_Vanetza_ITS2_ParkingStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OccupancyInformation.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "POIM-ParkingAvailability_ParkingReservationType.h"
#include "ParkingFeeType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_EuVehicleCategoryCode;
struct Vanetza_ITS2_LoadType;
struct Vanetza_ITS2_ParkingOccupancyInfo;

/* Vanetza_ITS2_ParkingStatus */
typedef struct Vanetza_ITS2_ParkingStatus {
	struct Vanetza_ITS2_ParkingStatus__vehicleTypes {
		A_SEQUENCE_OF(struct Vanetza_ITS2_EuVehicleCategoryCode) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleTypes;
	struct Vanetza_ITS2_ParkingStatus__reservationTypes {
		A_SEQUENCE_OF(Vanetza_ITS2_POIM_ParkingAvailability_ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationTypes;
	struct Vanetza_ITS2_ParkingStatus__loadTypes {
		A_SEQUENCE_OF(struct Vanetza_ITS2_LoadType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *loadTypes;
	struct Vanetza_ITS2_ParkingStatus__parkingFeeTypes {
		A_SEQUENCE_OF(Vanetza_ITS2_ParkingFeeType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *parkingFeeTypes;
	struct Vanetza_ITS2_ParkingStatus__occupancyTypes {
		A_SEQUENCE_OF(struct Vanetza_ITS2_ParkingOccupancyInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *occupancyTypes;
	Vanetza_ITS2_OccupancyInformation_t	 currentOccupancy;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ParkingStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ParkingStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_ParkingStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ParkingStatus_1[6];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_ParkingStatus_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ParkingStatus_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EuVehicleCategoryCode.h"
#include "LoadType.h"
#include "POIM-ParkingAvailability_ParkingOccupancyInfo.h"

#endif	/* _Vanetza_ITS2_ParkingStatus_H_ */
#include "asn_internal.h"
