/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "asn1/release2/TS103916v211/POIM-ParkingAvailability.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ParkingSpaceDetailed_H_
#define	_Vanetza_ITS2_ParkingSpaceDetailed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier2B.h"
#include "ParkingSpaceStatus.h"
#include "ParkingAreaArrangementType.h"
#include "ParkingOccupancyInfo.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "ParkingReservationType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_DeltaReferencePosition;
struct Vanetza_ITS2_DeltaPositions;
struct Vanetza_ITS2_Wgs84Angle;

/* Vanetza_ITS2_ParkingSpaceDetailed */
typedef struct Vanetza_ITS2_ParkingSpaceDetailed {
	Vanetza_ITS2_Identifier2B_t	 id;
	struct Vanetza_ITS2_DeltaReferencePosition	*location;	/* OPTIONAL */
	Vanetza_ITS2_ParkingSpaceStatus_t	 status;
	Vanetza_ITS2_ParkingAreaArrangementType_t	*arrangementType;	/* OPTIONAL */
	struct Vanetza_ITS2_DeltaPositions	*boundary;	/* OPTIONAL */
	struct Vanetza_ITS2_Wgs84Angle	*orientation;	/* OPTIONAL */
	Vanetza_ITS2_ParkingOccupancyInfo_t	 occupancyRule;
	Vanetza_ITS2_Identifier2B_t	*chargingStationId;	/* OPTIONAL */
	Vanetza_ITS2_Identifier2B_t	*accessViaLane;	/* OPTIONAL */
	struct Vanetza_ITS2_ParkingSpaceDetailed__accessViaParkingSpaces {
		A_SEQUENCE_OF(Vanetza_ITS2_Identifier2B_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accessViaParkingSpaces;
	struct Vanetza_ITS2_ParkingSpaceDetailed__reservationType {
		A_SEQUENCE_OF(Vanetza_ITS2_ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ParkingSpaceDetailed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ParkingSpaceDetailed;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_ParkingSpaceDetailed_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ParkingSpaceDetailed_1[11];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DeltaReferencePosition.h"
#include "DeltaPositions.h"
#include "Wgs84Angle.h"

#endif	/* _Vanetza_ITS2_ParkingSpaceDetailed_H_ */
#include "asn_internal.h"
