/*
 * Generated by asn1c
 * From ASN.1 module "POIM-PDU-Description"
 * 	found in "POIM-PDU-Description.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_PoiType_H_
#define	_Vanetza_ITS2_PoiType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_PoiType */
typedef long	 Vanetza_ITS2_PoiType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_PoiType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PoiType;
asn_struct_free_f Vanetza_ITS2_PoiType_free;
asn_struct_print_f Vanetza_ITS2_PoiType_print;
asn_constr_check_f Vanetza_ITS2_PoiType_constraint;
ber_type_decoder_f Vanetza_ITS2_PoiType_decode_ber;
der_type_encoder_f Vanetza_ITS2_PoiType_encode_der;
xer_type_decoder_f Vanetza_ITS2_PoiType_decode_xer;
xer_type_encoder_f Vanetza_ITS2_PoiType_encode_xer;
jer_type_encoder_f Vanetza_ITS2_PoiType_encode_jer;
oer_type_decoder_f Vanetza_ITS2_PoiType_decode_oer;
oer_type_encoder_f Vanetza_ITS2_PoiType_encode_oer;
per_type_decoder_f Vanetza_ITS2_PoiType_decode_uper;
per_type_encoder_f Vanetza_ITS2_PoiType_encode_uper;
per_type_decoder_f Vanetza_ITS2_PoiType_decode_aper;
per_type_encoder_f Vanetza_ITS2_PoiType_encode_aper;
#define Vanetza_ITS2_PoiType_parkingAvailability	((Vanetza_ITS2_PoiType_t)1)

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_PoiType_H_ */
#include "asn_internal.h"
