/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_PositioningSolutionType_H_
#define	_Vanetza_ITS2_PositioningSolutionType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_PositioningSolutionType {
	Vanetza_ITS2_PositioningSolutionType_noPositioningSolution	= 0,
	Vanetza_ITS2_PositioningSolutionType_sGNSS	= 1,
	Vanetza_ITS2_PositioningSolutionType_dGNSS	= 2,
	Vanetza_ITS2_PositioningSolutionType_sGNSSplusDR	= 3,
	Vanetza_ITS2_PositioningSolutionType_dGNSSplusDR	= 4,
	Vanetza_ITS2_PositioningSolutionType_dR	= 5,
	/*
	 * Enumeration is extensible
	 */
	Vanetza_ITS2_PositioningSolutionType_manuallyByOperator	= 6
} e_Vanetza_ITS2_PositioningSolutionType;

/* Vanetza_ITS2_PositioningSolutionType */
typedef long	 Vanetza_ITS2_PositioningSolutionType_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_PositioningSolutionType_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_PositioningSolutionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PositioningSolutionType;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_PositioningSolutionType_specs_1;
asn_struct_free_f Vanetza_ITS2_PositioningSolutionType_free;
asn_struct_print_f Vanetza_ITS2_PositioningSolutionType_print;
asn_constr_check_f Vanetza_ITS2_PositioningSolutionType_constraint;
ber_type_decoder_f Vanetza_ITS2_PositioningSolutionType_decode_ber;
der_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_der;
xer_type_decoder_f Vanetza_ITS2_PositioningSolutionType_decode_xer;
xer_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_xer;
jer_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_jer;
oer_type_decoder_f Vanetza_ITS2_PositioningSolutionType_decode_oer;
oer_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_oer;
per_type_decoder_f Vanetza_ITS2_PositioningSolutionType_decode_uper;
per_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_uper;
per_type_decoder_f Vanetza_ITS2_PositioningSolutionType_decode_aper;
per_type_encoder_f Vanetza_ITS2_PositioningSolutionType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_PositioningSolutionType_H_ */
#include "asn_internal.h"
