/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v221-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_RadialShapeDetails_H_
#define	_Vanetza_ITS2_RadialShapeDetails_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StandardLength12b.h"
#include "CartesianAngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_RadialShapeDetails */
typedef struct Vanetza_ITS2_RadialShapeDetails {
	Vanetza_ITS2_StandardLength12b_t	 range;
	Vanetza_ITS2_CartesianAngleValue_t	 horizontalOpeningAngleStart;
	Vanetza_ITS2_CartesianAngleValue_t	 horizontalOpeningAngleEnd;
	Vanetza_ITS2_CartesianAngleValue_t	*verticalOpeningAngleStart;	/* OPTIONAL */
	Vanetza_ITS2_CartesianAngleValue_t	*verticalOpeningAngleEnd;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_RadialShapeDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_RadialShapeDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_RadialShapeDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_RadialShapeDetails_1[5];
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_RadialShapeDetails_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_RadialShapeDetails_H_ */
#include "asn_internal.h"
