/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v241-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_RelevanceDistance_H_
#define	_Vanetza_ITS2_RelevanceDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_RelevanceDistance {
	Vanetza_ITS2_RelevanceDistance_lessThan50m	= 0,
	Vanetza_ITS2_RelevanceDistance_lessThan100m	= 1,
	Vanetza_ITS2_RelevanceDistance_lessThan200m	= 2,
	Vanetza_ITS2_RelevanceDistance_lessThan500m	= 3,
	Vanetza_ITS2_RelevanceDistance_lessThan1000m	= 4,
	Vanetza_ITS2_RelevanceDistance_lessThan5km	= 5,
	Vanetza_ITS2_RelevanceDistance_lessThan10km	= 6,
	Vanetza_ITS2_RelevanceDistance_over10km	= 7
} e_Vanetza_ITS2_RelevanceDistance;

/* Vanetza_ITS2_RelevanceDistance */
typedef long	 Vanetza_ITS2_RelevanceDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_RelevanceDistance;
asn_struct_free_f Vanetza_ITS2_RelevanceDistance_free;
asn_struct_print_f Vanetza_ITS2_RelevanceDistance_print;
asn_constr_check_f Vanetza_ITS2_RelevanceDistance_constraint;
ber_type_decoder_f Vanetza_ITS2_RelevanceDistance_decode_ber;
der_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_der;
xer_type_decoder_f Vanetza_ITS2_RelevanceDistance_decode_xer;
xer_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_xer;
jer_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_jer;
oer_type_decoder_f Vanetza_ITS2_RelevanceDistance_decode_oer;
oer_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_oer;
per_type_decoder_f Vanetza_ITS2_RelevanceDistance_decode_uper;
per_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_uper;
per_type_decoder_f Vanetza_ITS2_RelevanceDistance_decode_aper;
per_type_encoder_f Vanetza_ITS2_RelevanceDistance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_RelevanceDistance_H_ */
#include "asn_internal.h"
