/*
 * Generated by asn1c
 * From ASN.1 module "CPM-SensorInformationContainer"
 * 	found in "CPM-SensorInformationContainer.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_SensorInformation_H_
#define	_Vanetza_ITS2_SensorInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "SensorType.h"
#include "ConfidenceLevel.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_Shape;

/* Vanetza_ITS2_SensorInformation */
typedef struct Vanetza_ITS2_SensorInformation {
	Vanetza_ITS2_Identifier1B_t	 sensorId;
	Vanetza_ITS2_SensorType_t	 sensorType;
	struct Vanetza_ITS2_Shape	*perceptionRegionShape;	/* OPTIONAL */
	Vanetza_ITS2_ConfidenceLevel_t	*perceptionRegionConfidence;	/* OPTIONAL */
	BOOLEAN_t	 shadowingApplies;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_SensorInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_SensorInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_SensorInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_SensorInformation_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Shape.h"

#endif	/* _Vanetza_ITS2_SensorInformation_H_ */
#include "asn_internal.h"
