/*
 * Generated by asn1c
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "TS103900v231-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#include "TwoWheelerTypeSpecificInformation.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_TwoWheelerTypeSpecificInformation, choice.cyclist),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_CyclistTypeSpecificInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cyclist"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* cyclist */
};
asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_specs_1 = {
	sizeof(struct Vanetza_ITS2_TwoWheelerTypeSpecificInformation),
	offsetof(struct Vanetza_ITS2_TwoWheelerTypeSpecificInformation, _asn_ctx),
	offsetof(struct Vanetza_ITS2_TwoWheelerTypeSpecificInformation, present),
	sizeof(((struct Vanetza_ITS2_TwoWheelerTypeSpecificInformation *)0)->present),
	asn_MAP_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_TwoWheelerTypeSpecificInformation = {
	"TwoWheelerTypeSpecificInformation",
	"TwoWheelerTypeSpecificInformation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_1,
	1,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_TwoWheelerTypeSpecificInformation_specs_1	/* Additional specs */
};

