/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v241-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_UsageIndication_H_
#define	_Vanetza_ITS2_UsageIndication_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_UsageIndication {
	Vanetza_ITS2_UsageIndication_noIndication	= 0,
	Vanetza_ITS2_UsageIndication_specialUse	= 1,
	Vanetza_ITS2_UsageIndication_rescueOperation	= 2,
	/*
	 * Enumeration is extensible
	 */
	Vanetza_ITS2_UsageIndication_railroad	= 3,
	Vanetza_ITS2_UsageIndication_fixedRoute	= 4,
	Vanetza_ITS2_UsageIndication_restrictedRoute	= 5,
	Vanetza_ITS2_UsageIndication_adasAd	= 6,
	Vanetza_ITS2_UsageIndication_navigation	= 7
} e_Vanetza_ITS2_UsageIndication;

/* Vanetza_ITS2_UsageIndication */
typedef long	 Vanetza_ITS2_UsageIndication_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_UsageIndication_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_UsageIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_UsageIndication;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_UsageIndication_specs_1;
asn_struct_free_f Vanetza_ITS2_UsageIndication_free;
asn_struct_print_f Vanetza_ITS2_UsageIndication_print;
asn_constr_check_f Vanetza_ITS2_UsageIndication_constraint;
ber_type_decoder_f Vanetza_ITS2_UsageIndication_decode_ber;
der_type_encoder_f Vanetza_ITS2_UsageIndication_encode_der;
xer_type_decoder_f Vanetza_ITS2_UsageIndication_decode_xer;
xer_type_encoder_f Vanetza_ITS2_UsageIndication_encode_xer;
jer_type_encoder_f Vanetza_ITS2_UsageIndication_encode_jer;
oer_type_decoder_f Vanetza_ITS2_UsageIndication_decode_oer;
oer_type_encoder_f Vanetza_ITS2_UsageIndication_encode_oer;
per_type_decoder_f Vanetza_ITS2_UsageIndication_decode_uper;
per_type_encoder_f Vanetza_ITS2_UsageIndication_encode_uper;
per_type_decoder_f Vanetza_ITS2_UsageIndication_decode_aper;
per_type_encoder_f Vanetza_ITS2_UsageIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_UsageIndication_H_ */
#include "asn_internal.h"
