/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/release2/TS103300v221/VAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_VamParameters_H_
#define	_Vanetza_ITS2_VamParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainer.h"
#include "VruHighFrequencyContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_VruLowFrequencyContainer;
struct Vanetza_ITS2_VruClusterInformationContainer;
struct Vanetza_ITS2_VruClusterOperationContainer;
struct Vanetza_ITS2_VruMotionPredictionContainer;

/* Vanetza_ITS2_VamParameters */
typedef struct Vanetza_ITS2_VamParameters {
	Vanetza_ITS2_BasicContainer_t	 basicContainer;
	Vanetza_ITS2_VruHighFrequencyContainer_t	 vruHighFrequencyContainer;
	struct Vanetza_ITS2_VruLowFrequencyContainer	*vruLowFrequencyContainer;	/* OPTIONAL */
	struct Vanetza_ITS2_VruClusterInformationContainer	*vruClusterInformationContainer;	/* OPTIONAL */
	struct Vanetza_ITS2_VruClusterOperationContainer	*vruClusterOperationContainer;	/* OPTIONAL */
	struct Vanetza_ITS2_VruMotionPredictionContainer	*vruMotionPredictionContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_VamParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_VamParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_VamParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_VamParameters_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VruLowFrequencyContainer.h"
#include "VruClusterInformationContainer.h"
#include "VruClusterOperationContainer.h"
#include "VruMotionPredictionContainer.h"

#endif	/* _Vanetza_ITS2_VamParameters_H_ */
#include "asn_internal.h"
