/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v241-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_VruExteriorLights_H_
#define	_Vanetza_ITS2_VruExteriorLights_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ExteriorLights.h"
#include "VruSpecificExteriorLights.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_VruExteriorLights */
typedef struct Vanetza_ITS2_VruExteriorLights {
	Vanetza_ITS2_ExteriorLights_t	 vehicular;
	Vanetza_ITS2_VruSpecificExteriorLights_t	 vruSpecific;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_VruExteriorLights_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_VruExteriorLights;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_VruExteriorLights_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_VruExteriorLights_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_VruExteriorLights_H_ */
#include "asn_internal.h"
