/*
 * Generated by asn1c
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "TS103900v231-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#include "WrappedExtensionContainer.h"

static const long asn_VAL_1_Vanetza_ITS2_twoWheelerContainer = 1;
static const long asn_VAL_2_Vanetza_ITS2_eHorizonLocationSharingContainer = 2;
static const long asn_VAL_3_Vanetza_ITS2_veryLowFrequencyContainer = 3;
static const long asn_VAL_4_Vanetza_ITS2_pathPredictionContainer = 4;
static const long asn_VAL_5_Vanetza_ITS2_generalizedLanePositionsContainer = 5;
static const long asn_VAL_6_Vanetza_ITS2_vehicleMovementControlContainer = 6;
static const asn_ioc_cell_t asn_IOS_Vanetza_ITS2_ExtensionContainers_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_1_Vanetza_ITS2_twoWheelerContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_TwoWheelerContainer },
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_2_Vanetza_ITS2_eHorizonLocationSharingContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_EHorizonLocationSharingContainer },
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_3_Vanetza_ITS2_veryLowFrequencyContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_VeryLowFrequencyContainer },
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_4_Vanetza_ITS2_pathPredictionContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_PathPredictionContainer },
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_5_Vanetza_ITS2_generalizedLanePositionsContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_GeneralizedLanePositionsContainer },
	{ "&id", aioc__value, &asn_DEF_Vanetza_ITS2_ExtensionContainerId, &asn_VAL_6_Vanetza_ITS2_vehicleMovementControlContainer },
	{ "&Type", aioc__type, &asn_DEF_Vanetza_ITS2_VehicleMovementControlContainer }
};
static const asn_ioc_set_t asn_IOS_Vanetza_ITS2_ExtensionContainers_1[] = {
	{ 6, 2, asn_IOS_Vanetza_ITS2_ExtensionContainers_1_rows }
};
static int
memb_Vanetza_ITS2_containerId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1L && value <= 16L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_WrappedExtensionContainer_Vanetza_ITS2_containerData_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_Vanetza_ITS2_ExtensionContainers_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Type */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, containerId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_Vanetza_ITS2_containerData_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_Vanetza_ITS2_containerId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (1..16) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_Vanetza_ITS2_containerId_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_Vanetza_ITS2_containerData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_Vanetza_ITS2_containerData_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_Vanetza_ITS2_containerData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.TwoWheelerContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_TwoWheelerContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"TwoWheelerContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.EHorizonLocationSharingContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_EHorizonLocationSharingContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"EHorizonLocationSharingContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.VeryLowFrequencyContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_VeryLowFrequencyContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"VeryLowFrequencyContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.PathPredictionContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_PathPredictionContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"PathPredictionContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.GeneralizedLanePositionsContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_GeneralizedLanePositionsContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"GeneralizedLanePositionsContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.VehicleMovementControlContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_VehicleMovementControlContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"VehicleMovementControlContainer"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_containerData_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 5 }, /* TwoWheelerContainer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 4 }, /* EHorizonLocationSharingContainer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 3 }, /* VeryLowFrequencyContainer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 2 }, /* PathPredictionContainer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 1 }, /* GeneralizedLanePositionsContainer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 0 } /* VehicleMovementControlContainer */
};
static asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_containerData_specs_3 = {
	sizeof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, _asn_ctx),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, present),
	sizeof(((struct Vanetza_ITS2_WrappedExtensionContainer__containerData *)0)->present),
	asn_MAP_Vanetza_ITS2_containerData_tag2el_3,
	6,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_containerData_3 = {
	"containerData",
	"containerData",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_Vanetza_ITS2_containerData_3,
	6,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_containerData_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_WrappedExtensionContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, containerId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_ExtensionContainerId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_Vanetza_ITS2_containerId_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_Vanetza_ITS2_containerId_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_Vanetza_ITS2_containerId_constraint_1
		},
		0, 0, /* No default value */
		"containerId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, containerData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_containerData_3,
		select_WrappedExtensionContainer_Vanetza_ITS2_containerData_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_Vanetza_ITS2_containerData_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_Vanetza_ITS2_containerData_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_Vanetza_ITS2_containerData_constraint_1
		},
		0, 0, /* No default value */
		"containerData"
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_WrappedExtensionContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* containerId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* containerData */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_WrappedExtensionContainer_specs_1 = {
	sizeof(struct Vanetza_ITS2_WrappedExtensionContainer),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, _asn_ctx),
	asn_MAP_Vanetza_ITS2_WrappedExtensionContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_WrappedExtensionContainer = {
	"WrappedExtensionContainer",
	"WrappedExtensionContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_WrappedExtensionContainer_1,
	2,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_WrappedExtensionContainer_specs_1	/* Additional specs */
};

