/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "asn1/IEEE1609dot2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Countersignature_H_
#define	_Countersignature_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Countersignature */
typedef Ieee1609Dot2Data_t	 Countersignature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Countersignature;
asn_struct_free_f Countersignature_free;
asn_struct_print_f Countersignature_print;
asn_constr_check_f Countersignature_constraint;
ber_type_decoder_f Countersignature_decode_ber;
der_type_encoder_f Countersignature_encode_der;
xer_type_decoder_f Countersignature_decode_xer;
xer_type_encoder_f Countersignature_encode_xer;
oer_type_decoder_f Countersignature_decode_oer;
oer_type_encoder_f Countersignature_encode_oer;
per_type_decoder_f Countersignature_decode_uper;
per_type_encoder_f Countersignature_encode_uper;
per_type_decoder_f Countersignature_decode_aper;
per_type_encoder_f Countersignature_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Countersignature_H_ */
#include "asn_internal.h"
