/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "asn1/TS102941v131-TrustLists.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ToBeSignedRcaCtl_H_
#define	_ToBeSignedRcaCtl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CtlFormat.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedRcaCtl */
typedef CtlFormat_t	 ToBeSignedRcaCtl_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ToBeSignedRcaCtl_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedRcaCtl;
asn_struct_free_f ToBeSignedRcaCtl_free;
asn_struct_print_f ToBeSignedRcaCtl_print;
asn_constr_check_f ToBeSignedRcaCtl_constraint;
ber_type_decoder_f ToBeSignedRcaCtl_decode_ber;
der_type_encoder_f ToBeSignedRcaCtl_encode_der;
xer_type_decoder_f ToBeSignedRcaCtl_decode_xer;
xer_type_encoder_f ToBeSignedRcaCtl_encode_xer;
oer_type_decoder_f ToBeSignedRcaCtl_decode_oer;
oer_type_encoder_f ToBeSignedRcaCtl_encode_oer;
per_type_decoder_f ToBeSignedRcaCtl_decode_uper;
per_type_encoder_f ToBeSignedRcaCtl_encode_uper;
per_type_decoder_f ToBeSignedRcaCtl_decode_aper;
per_type_encoder_f ToBeSignedRcaCtl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedRcaCtl_H_ */
#include "asn_internal.h"
