/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941BaseTypes"
 * 	found in "asn1/TS102941v131-BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Version_H_
#define	_Version_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Version {
	Version_v1	= 1
} e_Version;

/* Version */
typedef long	 Version_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Version;
asn_struct_free_f Version_free;
asn_struct_print_f Version_print;
asn_constr_check_f Version_constraint;
ber_type_decoder_f Version_decode_ber;
der_type_encoder_f Version_encode_der;
xer_type_decoder_f Version_decode_xer;
xer_type_encoder_f Version_encode_xer;
oer_type_decoder_f Version_decode_oer;
oer_type_encoder_f Version_encode_oer;
per_type_decoder_f Version_decode_uper;
per_type_encoder_f Version_encode_uper;
per_type_decoder_f Version_decode_aper;
per_type_encoder_f Version_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Version_H_ */
#include "asn_internal.h"
