var namespaces_dup =
[
    [ "std", "d8/dcc/namespacestd.html", null ],
    [ "vanetza", null, [
      [ "access", null, [
        [ "ieee802", null, [
          [ "dot11", null, [
            [ "FrameControl", "d6/d0d/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1FrameControl.html", "d6/d0d/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1FrameControl" ],
            [ "QosControl", "d6/d0c/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1QosControl.html", "d6/d0c/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1QosControl" ],
            [ "QosDataHeader", "d9/d29/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1QosDataHeader.html", "d9/d29/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1QosDataHeader" ],
            [ "SequenceControl", "d3/d27/structvanetza_1_1access_1_1ieee802_1_1dot11_1_1SequenceControl.html", null ]
          ] ],
          [ "LlcSnapHeader", "d2/d24/structvanetza_1_1access_1_1ieee802_1_1LlcSnapHeader.html", null ]
        ] ],
        [ "DataRateG5", "d3/dbb/classvanetza_1_1access_1_1DataRateG5.html", "d3/dbb/classvanetza_1_1access_1_1DataRateG5" ],
        [ "DataRequest", "de/df3/structvanetza_1_1access_1_1DataRequest.html", null ],
        [ "G5LinkLayer", "dc/d63/structvanetza_1_1access_1_1G5LinkLayer.html", null ],
        [ "Interface", "de/d85/classvanetza_1_1access_1_1Interface.html", null ],
        [ "AccessCategory", "d5/d63/access__category_8hpp.html#ab33e8093f166984624af22f564bd0a4c", [
          [ "BK", "d5/d63/access__category_8hpp.html#ab33e8093f166984624af22f564bd0a4ca3b16c9d4c4c856ce7fff405e3b6c43ab", null ],
          [ "BE", "d5/d63/access__category_8hpp.html#ab33e8093f166984624af22f564bd0a4cad3dcf429c679f9af82eb9a3b31c4df44", null ],
          [ "VI", "d5/d63/access__category_8hpp.html#ab33e8093f166984624af22f564bd0a4ca893015dbee3ceb57a09c96ef71045081", null ],
          [ "VO", "d5/d63/access__category_8hpp.html#ab33e8093f166984624af22f564bd0a4cae984ea8be853e1e6c3313e8e1d7eb849", null ]
        ] ]
      ] ],
      [ "asio", null, [
        [ "cohda", "d5/d3a/classvanetza_1_1asio_1_1cohda.html", null ],
        [ "linklayer_endpoint", "d5/d62/classvanetza_1_1asio_1_1linklayer__endpoint.html", "d5/d62/classvanetza_1_1asio_1_1linklayer__endpoint" ]
      ] ],
      [ "asn1", null, [
        [ "asn1c_oer_wrapper", "de/dbf/classvanetza_1_1asn1_1_1asn1c__oer__wrapper.html", "de/dbf/classvanetza_1_1asn1_1_1asn1c__oer__wrapper" ],
        [ "asn1c_per_wrapper", "dc/dbf/classvanetza_1_1asn1_1_1asn1c__per__wrapper.html", "dc/dbf/classvanetza_1_1asn1_1_1asn1c__per__wrapper" ],
        [ "asn1c_wrapper_common", "d0/d68/classvanetza_1_1asn1_1_1asn1c__wrapper__common.html", "d0/d68/classvanetza_1_1asn1_1_1asn1c__wrapper__common" ],
        [ "Cam", "d6/d47/classvanetza_1_1asn1_1_1Cam.html", "d6/d47/classvanetza_1_1asn1_1_1Cam" ],
        [ "Cpm", "d3/d6a/classvanetza_1_1asn1_1_1Cpm.html", "d3/d6a/classvanetza_1_1asn1_1_1Cpm" ],
        [ "Denm", "da/dbc/classvanetza_1_1asn1_1_1Denm.html", "da/dbc/classvanetza_1_1asn1_1_1Denm" ],
        [ "Mapem", "d4/dfa/classvanetza_1_1asn1_1_1Mapem.html", "d4/dfa/classvanetza_1_1asn1_1_1Mapem" ],
        [ "PacketVisitor", "d5/d3f/classvanetza_1_1asn1_1_1PacketVisitor.html", "d5/d3f/classvanetza_1_1asn1_1_1PacketVisitor" ],
        [ "Spatem", "d4/d0f/classvanetza_1_1asn1_1_1Spatem.html", "d4/d0f/classvanetza_1_1asn1_1_1Spatem" ]
      ] ],
      [ "btp", null, [
        [ "DataIndication", "da/ddd/structvanetza_1_1btp_1_1DataIndication.html", null ],
        [ "DataRequestA", "d5/d92/structvanetza_1_1btp_1_1DataRequestA.html", null ],
        [ "DataRequestB", "d1/d61/structvanetza_1_1btp_1_1DataRequestB.html", null ],
        [ "DataRequestGeoNetParams", "d0/d0f/structvanetza_1_1btp_1_1DataRequestGeoNetParams.html", null ],
        [ "HeaderA", "d4/d2d/structvanetza_1_1btp_1_1HeaderA.html", null ],
        [ "HeaderB", "d2/d5f/structvanetza_1_1btp_1_1HeaderB.html", null ],
        [ "IndicationInterface", "df/dd3/classvanetza_1_1btp_1_1IndicationInterface.html", null ],
        [ "PortDispatcher", "d0/d42/classvanetza_1_1btp_1_1PortDispatcher.html", "d0/d42/classvanetza_1_1btp_1_1PortDispatcher" ],
        [ "RequestInterface", "d1/df3/classvanetza_1_1btp_1_1RequestInterface.html", null ]
      ] ],
      [ "convertible", null, [
        [ "byte_buffer", "d4/dce/structvanetza_1_1convertible_1_1byte__buffer.html", null ],
        [ "byte_buffer_impl", "d7/deb/structvanetza_1_1convertible_1_1byte__buffer__impl.html", null ],
        [ "byte_buffer_impl< btp::HeaderA >", "d2/d99/structvanetza_1_1convertible_1_1byte__buffer__impl_3_01btp_1_1HeaderA_01_4.html", null ],
        [ "byte_buffer_impl< btp::HeaderB >", "d8/dda/structvanetza_1_1convertible_1_1byte__buffer__impl_3_01btp_1_1HeaderB_01_4.html", null ],
        [ "byte_buffer_impl< ByteBuffer >", "d9/d3a/structvanetza_1_1convertible_1_1byte__buffer__impl_3_01ByteBuffer_01_4.html", null ],
        [ "byte_buffer_impl< geonet::SecuredPdu >", "da/dac/structvanetza_1_1convertible_1_1byte__buffer__impl_3_01geonet_1_1SecuredPdu_01_4.html", null ]
      ] ],
      [ "dcc", null, [
        [ "Active", "de/d96/classvanetza_1_1dcc_1_1Active.html", null ],
        [ "BurstBudget", "db/db1/classvanetza_1_1dcc_1_1BurstBudget.html", "db/db1/classvanetza_1_1dcc_1_1BurstBudget" ],
        [ "BurstyTransmitRateControl", "d1/d1c/classvanetza_1_1dcc_1_1BurstyTransmitRateControl.html", "d1/d1c/classvanetza_1_1dcc_1_1BurstyTransmitRateControl" ],
        [ "ChannelLoad", "dc/d86/classvanetza_1_1dcc_1_1ChannelLoad.html", "dc/d86/classvanetza_1_1dcc_1_1ChannelLoad" ],
        [ "ChannelProbeProcessor", "d5/d39/classvanetza_1_1dcc_1_1ChannelProbeProcessor.html", "d5/d39/classvanetza_1_1dcc_1_1ChannelProbeProcessor" ],
        [ "DataRequest", "de/d0a/structvanetza_1_1dcc_1_1DataRequest.html", null ],
        [ "DutyCyclePermit", "de/d04/classvanetza_1_1dcc_1_1DutyCyclePermit.html", "de/d04/classvanetza_1_1dcc_1_1DutyCyclePermit" ],
        [ "Entity", "db/d18/classvanetza_1_1dcc_1_1Entity.html", "db/d18/classvanetza_1_1dcc_1_1Entity" ],
        [ "FlowControl", "d8/da4/classvanetza_1_1dcc_1_1FlowControl.html", "d8/da4/classvanetza_1_1dcc_1_1FlowControl" ],
        [ "FullyMeshedStateMachine", "d2/d3b/classvanetza_1_1dcc_1_1FullyMeshedStateMachine.html", "d2/d3b/classvanetza_1_1dcc_1_1FullyMeshedStateMachine" ],
        [ "GradualStateMachine", "df/dd9/classvanetza_1_1dcc_1_1GradualStateMachine.html", "df/dd9/classvanetza_1_1dcc_1_1GradualStateMachine" ],
        [ "HookedChannelProbeProcessor", "d5/d0e/classvanetza_1_1dcc_1_1HookedChannelProbeProcessor.html", "d5/d0e/classvanetza_1_1dcc_1_1HookedChannelProbeProcessor" ],
        [ "Limeric", "d0/dc9/classvanetza_1_1dcc_1_1Limeric.html", "d0/dc9/classvanetza_1_1dcc_1_1Limeric" ],
        [ "LimericBudget", "d8/d7e/classvanetza_1_1dcc_1_1LimericBudget.html", "d8/d7e/classvanetza_1_1dcc_1_1LimericBudget" ],
        [ "LimericTransmitRateControl", "df/d62/classvanetza_1_1dcc_1_1LimericTransmitRateControl.html", "df/d62/classvanetza_1_1dcc_1_1LimericTransmitRateControl" ],
        [ "NullRequestInterface", "d3/d6b/classvanetza_1_1dcc_1_1NullRequestInterface.html", null ],
        [ "Relaxed", "da/d03/classvanetza_1_1dcc_1_1Relaxed.html", null ],
        [ "RequestInterface", "db/d5b/classvanetza_1_1dcc_1_1RequestInterface.html", null ],
        [ "Restrictive", "de/d46/classvanetza_1_1dcc_1_1Restrictive.html", null ],
        [ "SingleReactiveTransmitRateControl", "dc/d2b/classvanetza_1_1dcc_1_1SingleReactiveTransmitRateControl.html", "dc/d2b/classvanetza_1_1dcc_1_1SingleReactiveTransmitRateControl" ],
        [ "SmoothingChannelProbeProcessor", "d2/d7c/classvanetza_1_1dcc_1_1SmoothingChannelProbeProcessor.html", "d2/d7c/classvanetza_1_1dcc_1_1SmoothingChannelProbeProcessor" ],
        [ "State", "d9/d97/classvanetza_1_1dcc_1_1State.html", null ],
        [ "StateMachine", "d8/db3/classvanetza_1_1dcc_1_1StateMachine.html", "d8/db3/classvanetza_1_1dcc_1_1StateMachine" ],
        [ "StateMachineBudget", "d0/d6b/classvanetza_1_1dcc_1_1StateMachineBudget.html", null ],
        [ "Transmission", "df/dd5/classvanetza_1_1dcc_1_1Transmission.html", null ],
        [ "TransmissionLite", "dc/da1/structvanetza_1_1dcc_1_1TransmissionLite.html", null ],
        [ "TransmitRateControl", "de/d9c/classvanetza_1_1dcc_1_1TransmitRateControl.html", "de/d9c/classvanetza_1_1dcc_1_1TransmitRateControl" ],
        [ "TransmitRateFeedback", "d2/d13/classvanetza_1_1dcc_1_1TransmitRateFeedback.html", "d2/d13/classvanetza_1_1dcc_1_1TransmitRateFeedback" ],
        [ "TransmitRateThrottle", "dd/dbf/classvanetza_1_1dcc_1_1TransmitRateThrottle.html", "dd/dbf/classvanetza_1_1dcc_1_1TransmitRateThrottle" ]
      ] ],
      [ "detail", null, [
        [ "EndianConverter", "d1/d1a/structvanetza_1_1detail_1_1EndianConverter.html", null ],
        [ "EndianConverter< T, ByteOrder::BigEndian, ByteOrder::LittleEndian >", "d2/dfe/structvanetza_1_1detail_1_1EndianConverter_3_01T_00_01ByteOrder_1_1BigEndian_00_01ByteOrder_1_1LittleEndian_01_4.html", null ],
        [ "EndianConverter< T, ByteOrder::LittleEndian, ByteOrder::BigEndian >", "de/de8/structvanetza_1_1detail_1_1EndianConverter_3_01T_00_01ByteOrder_1_1LittleEndian_00_01ByteOrder_1_1BigEndian_01_4.html", null ],
        [ "EndianConverter< T, ORDER, ORDER >", "dd/def/structvanetza_1_1detail_1_1EndianConverter_3_01T_00_01ORDER_00_01ORDER_01_4.html", null ]
      ] ],
      [ "facilities", null, [
        [ "PathHistory", "d3/d9f/classvanetza_1_1facilities_1_1PathHistory.html", "d3/d9f/classvanetza_1_1facilities_1_1PathHistory" ],
        [ "PathPoint", "d9/d23/structvanetza_1_1facilities_1_1PathPoint.html", null ]
      ] ],
      [ "geonet", null, [
        [ "detail", null, [
          [ "GbcGacHeader", "dc/dc6/structvanetza_1_1geonet_1_1detail_1_1GbcGacHeader.html", null ]
        ] ],
        [ "packet_buffer", null, [
          [ "Data", "d4/dce/classvanetza_1_1geonet_1_1packet__buffer_1_1Data.html", "d4/dce/classvanetza_1_1geonet_1_1packet__buffer_1_1Data" ],
          [ "Expiry", "db/d58/classvanetza_1_1geonet_1_1packet__buffer_1_1Expiry.html", null ]
        ] ],
        [ "Address", "da/ddb/classvanetza_1_1geonet_1_1Address.html", null ],
        [ "Area", "d3/d12/structvanetza_1_1geonet_1_1Area.html", null ],
        [ "BasicHeader", "d5/db0/structvanetza_1_1geonet_1_1BasicHeader.html", null ],
        [ "BeaconHeader", "d5/d19/structvanetza_1_1geonet_1_1BeaconHeader.html", null ],
        [ "CartesianPosition", "dd/db0/structvanetza_1_1geonet_1_1CartesianPosition.html", null ],
        [ "CbfCounter", "db/d2d/classvanetza_1_1geonet_1_1CbfCounter.html", "db/d2d/classvanetza_1_1geonet_1_1CbfCounter" ],
        [ "CbfCounterContending", "da/d5f/classvanetza_1_1geonet_1_1CbfCounterContending.html", "da/d5f/classvanetza_1_1geonet_1_1CbfCounterContending" ],
        [ "CbfCounterFading", "d4/d50/classvanetza_1_1geonet_1_1CbfCounterFading.html", "d4/d50/classvanetza_1_1geonet_1_1CbfCounterFading" ],
        [ "CbfCounterImmortal", "db/d11/classvanetza_1_1geonet_1_1CbfCounterImmortal.html", "db/d11/classvanetza_1_1geonet_1_1CbfCounterImmortal" ],
        [ "CbfPacket", "d6/dc2/classvanetza_1_1geonet_1_1CbfPacket.html", "d6/dc2/classvanetza_1_1geonet_1_1CbfPacket" ],
        [ "CbfPacketBuffer", "d3/d15/classvanetza_1_1geonet_1_1CbfPacketBuffer.html", "d3/d15/classvanetza_1_1geonet_1_1CbfPacketBuffer" ],
        [ "CbrAggregator", "d4/db1/classvanetza_1_1geonet_1_1CbrAggregator.html", "d4/db1/classvanetza_1_1geonet_1_1CbrAggregator" ],
        [ "Circle", "d3/d68/structvanetza_1_1geonet_1_1Circle.html", null ],
        [ "CommonHeader", "d1/d63/structvanetza_1_1geonet_1_1CommonHeader.html", null ],
        [ "ConstAccessiblePdu", "da/dcb/classvanetza_1_1geonet_1_1ConstAccessiblePdu.html", null ],
        [ "DataConfirm", "d6/d43/structvanetza_1_1geonet_1_1DataConfirm.html", null ],
        [ "DataIndication", "d9/dcb/structvanetza_1_1geonet_1_1DataIndication.html", null ],
        [ "DataRequest", "d1/d1f/structvanetza_1_1geonet_1_1DataRequest.html", "d1/d1f/structvanetza_1_1geonet_1_1DataRequest" ],
        [ "DataRequestWithAddress", "d4/d96/structvanetza_1_1geonet_1_1DataRequestWithAddress.html", null ],
        [ "DataRequestWithArea", "d9/d1d/structvanetza_1_1geonet_1_1DataRequestWithArea.html", null ],
        [ "DccFieldGenerator", "d2/d6f/classvanetza_1_1geonet_1_1DccFieldGenerator.html", null ],
        [ "DccInformationSharing", "d4/d6e/classvanetza_1_1geonet_1_1DccInformationSharing.html", "d4/d6e/classvanetza_1_1geonet_1_1DccInformationSharing" ],
        [ "DccMcoField", "d0/d60/classvanetza_1_1geonet_1_1DccMcoField.html", "d0/d60/classvanetza_1_1geonet_1_1DccMcoField" ],
        [ "DuplicatePacketList", "d9/d84/classvanetza_1_1geonet_1_1DuplicatePacketList.html", "d9/d84/classvanetza_1_1geonet_1_1DuplicatePacketList" ],
        [ "Ellipse", "d2/d2e/structvanetza_1_1geonet_1_1Ellipse.html", null ],
        [ "ExtendedPdu", "d9/d6e/classvanetza_1_1geonet_1_1ExtendedPdu.html", null ],
        [ "ExtendedPduConstRefs", "d5/d01/classvanetza_1_1geonet_1_1ExtendedPduConstRefs.html", null ],
        [ "GacDataRequest", "d7/d84/structvanetza_1_1geonet_1_1GacDataRequest.html", null ],
        [ "GbcDataRequest", "de/d7b/structvanetza_1_1geonet_1_1GbcDataRequest.html", null ],
        [ "GbcMemory", "d1/d8e/classvanetza_1_1geonet_1_1GbcMemory.html", "d1/d8e/classvanetza_1_1geonet_1_1GbcMemory" ],
        [ "GeoBroadcastHeader", "d1/db9/structvanetza_1_1geonet_1_1GeoBroadcastHeader.html", null ],
        [ "GeodeticPosition", "d0/da6/structvanetza_1_1geonet_1_1GeodeticPosition.html", null ],
        [ "GeoUnicastHeader", "d2/d16/structvanetza_1_1geonet_1_1GeoUnicastHeader.html", null ],
        [ "GucDataRequest", "d0/db3/structvanetza_1_1geonet_1_1GucDataRequest.html", null ],
        [ "IndicationContext", "d0/db4/classvanetza_1_1geonet_1_1IndicationContext.html", "d0/db4/classvanetza_1_1geonet_1_1IndicationContext" ],
        [ "IndicationContextBasic", "d6/d4a/classvanetza_1_1geonet_1_1IndicationContextBasic.html", "d6/d4a/classvanetza_1_1geonet_1_1IndicationContextBasic" ],
        [ "IndicationContextCast", "dc/dad/classvanetza_1_1geonet_1_1IndicationContextCast.html", "dc/dad/classvanetza_1_1geonet_1_1IndicationContextCast" ],
        [ "IndicationContextDeserialize", "dd/d8e/classvanetza_1_1geonet_1_1IndicationContextDeserialize.html", "dd/d8e/classvanetza_1_1geonet_1_1IndicationContextDeserialize" ],
        [ "IndicationContextSecured", "db/d97/classvanetza_1_1geonet_1_1IndicationContextSecured.html", "db/d97/classvanetza_1_1geonet_1_1IndicationContextSecured" ],
        [ "IndicationContextSecuredCast", "db/d0c/classvanetza_1_1geonet_1_1IndicationContextSecuredCast.html", "db/d0c/classvanetza_1_1geonet_1_1IndicationContextSecuredCast" ],
        [ "IndicationContextSecuredDeserialize", "d4/d6d/classvanetza_1_1geonet_1_1IndicationContextSecuredDeserialize.html", "d4/d6d/classvanetza_1_1geonet_1_1IndicationContextSecuredDeserialize" ],
        [ "Lifetime", "d7/d9a/classvanetza_1_1geonet_1_1Lifetime.html", "d7/d9a/classvanetza_1_1geonet_1_1Lifetime" ],
        [ "LinkLayer", "dd/df3/structvanetza_1_1geonet_1_1LinkLayer.html", null ],
        [ "LocationTable", "db/d5b/classvanetza_1_1geonet_1_1LocationTable.html", null ],
        [ "LocationTableEntry", "d7/d6e/classvanetza_1_1geonet_1_1LocationTableEntry.html", "d7/d6e/classvanetza_1_1geonet_1_1LocationTableEntry" ],
        [ "LocationTableEntryCreator", "d7/d45/classvanetza_1_1geonet_1_1LocationTableEntryCreator.html", null ],
        [ "LocTEX_G5", "d2/d76/structvanetza_1_1geonet_1_1LocTEX__G5.html", null ],
        [ "LongPositionVector", "df/d7e/classvanetza_1_1geonet_1_1LongPositionVector.html", null ],
        [ "LsReplyHeader", "d9/dcc/structvanetza_1_1geonet_1_1LsReplyHeader.html", null ],
        [ "LsRequestHeader", "d5/de0/structvanetza_1_1geonet_1_1LsRequestHeader.html", null ],
        [ "ManagementInformationBase", "dd/dbb/structvanetza_1_1geonet_1_1ManagementInformationBase.html", null ],
        [ "NextHop", "db/dd9/classvanetza_1_1geonet_1_1NextHop.html", "db/dd9/classvanetza_1_1geonet_1_1NextHop" ],
        [ "NullDccFieldGenerator", "d1/dd1/classvanetza_1_1geonet_1_1NullDccFieldGenerator.html", null ],
        [ "PacketBuffer", "de/d48/classvanetza_1_1geonet_1_1PacketBuffer.html", "de/d48/classvanetza_1_1geonet_1_1PacketBuffer" ],
        [ "Parser", "d1/da6/classvanetza_1_1geonet_1_1Parser.html", null ],
        [ "Pdu", "dc/d8c/classvanetza_1_1geonet_1_1Pdu.html", null ],
        [ "PendingPacket", "d6/d26/classvanetza_1_1geonet_1_1PendingPacket.html", null ],
        [ "PositionUpdater", "d2/d42/classvanetza_1_1geonet_1_1PositionUpdater.html", "d2/d42/classvanetza_1_1geonet_1_1PositionUpdater" ],
        [ "Rectangle", "df/d32/structvanetza_1_1geonet_1_1Rectangle.html", null ],
        [ "Repeater", "db/d33/classvanetza_1_1geonet_1_1Repeater.html", "db/d33/classvanetza_1_1geonet_1_1Repeater" ],
        [ "RepetitionDispatcher", "dc/ddc/classvanetza_1_1geonet_1_1RepetitionDispatcher.html", null ],
        [ "Router", "d9/d48/classvanetza_1_1geonet_1_1Router.html", "d9/d48/classvanetza_1_1geonet_1_1Router" ],
        [ "SecuredPdu", "d6/d63/classvanetza_1_1geonet_1_1SecuredPdu.html", null ],
        [ "SequenceNumber", "de/d8f/classvanetza_1_1geonet_1_1SequenceNumber.html", null ],
        [ "ShbDataRequest", "d0/d57/structvanetza_1_1geonet_1_1ShbDataRequest.html", null ],
        [ "ShbHeader", "d0/d9f/structvanetza_1_1geonet_1_1ShbHeader.html", null ],
        [ "ShortPositionVector", "d1/dec/classvanetza_1_1geonet_1_1ShortPositionVector.html", null ],
        [ "SoftStateDefaultCreator", "db/dd8/structvanetza_1_1geonet_1_1SoftStateDefaultCreator.html", null ],
        [ "SoftStateMap", "dd/dab/classvanetza_1_1geonet_1_1SoftStateMap.html", "dd/dab/classvanetza_1_1geonet_1_1SoftStateMap" ],
        [ "Timestamp", "d0/dc8/classvanetza_1_1geonet_1_1Timestamp.html", "d0/dc8/classvanetza_1_1geonet_1_1Timestamp" ],
        [ "TrafficClass", "d3/d97/classvanetza_1_1geonet_1_1TrafficClass.html", null ],
        [ "TransportInterface", "d2/dde/classvanetza_1_1geonet_1_1TransportInterface.html", null ],
        [ "TsbDataRequest", "d4/d19/structvanetza_1_1geonet_1_1TsbDataRequest.html", null ],
        [ "TsbHeader", "d6/d42/structvanetza_1_1geonet_1_1TsbHeader.html", null ],
        [ "VariantPdu", "d7/d84/classvanetza_1_1geonet_1_1VariantPdu.html", null ]
      ] ],
      [ "pdu_tags", null, [
        [ "empty_pdu_tag", "db/d41/structvanetza_1_1pdu__tags_1_1empty__pdu__tag.html", null ],
        [ "ethernet_tag", "d9/df4/structvanetza_1_1pdu__tags_1_1ethernet__tag.html", null ],
        [ "mac_tag", "d0/df3/structvanetza_1_1pdu__tags_1_1mac__tag.html", null ],
        [ "mk2_tag", "d5/d6d/structvanetza_1_1pdu__tags_1_1mk2__tag.html", null ],
        [ "pdu_tag", "d5/d0a/structvanetza_1_1pdu__tags_1_1pdu__tag.html", null ],
        [ "phy_tag", "dd/de8/structvanetza_1_1pdu__tags_1_1phy__tag.html", null ]
      ] ],
      [ "security", null, [
        [ "detail", null, [
          [ "subject_attribute_type", "df/d81/structvanetza_1_1security_1_1detail_1_1subject__attribute__type.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::Assurance_Level >", "da/d33/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Assurance__Level_01_4.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::Encryption_Key >", "df/d06/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Encryption__Key_01_4.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::ITS_AID_List >", "d8/df4/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1ITS__AID__List_01_4.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::ITS_AID_SSP_List >", "de/ddb/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1ITS__AID__SSP__List_01_4.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::Reconstruction_Value >", "da/d64/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Reconstruction__Value_01_4.html", null ],
          [ "subject_attribute_type< SubjectAttributeType::Verification_Key >", "da/df8/structvanetza_1_1security_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Verification__Key_01_4.html", null ],
          [ "validity_restriction_type", "d1/dac/structvanetza_1_1security_1_1detail_1_1validity__restriction__type.html", null ],
          [ "validity_restriction_type< ValidityRestrictionType::Region >", "d7/d0c/structvanetza_1_1security_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_1_1Region_01_4.html", null ],
          [ "validity_restriction_type< ValidityRestrictionType::Time_End >", "da/d12/structvanetza_1_1security_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_1_1Time__End_01_4.html", null ],
          [ "validity_restriction_type< ValidityRestrictionType::Time_Start_And_Duration >", "dd/d8c/structvanetza_1_1security_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_110ffbde126a6e3f210790987e2371478.html", null ],
          [ "validity_restriction_type< ValidityRestrictionType::Time_Start_And_End >", "d1/d8b/structvanetza_1_1security_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_1_1Time__Start__And__End_01_4.html", null ]
        ] ],
        [ "ecdsa256", null, [
          [ "KeyPair", "d2/d2a/structvanetza_1_1security_1_1ecdsa256_1_1KeyPair.html", null ],
          [ "PrivateKey", "d6/dcf/structvanetza_1_1security_1_1ecdsa256_1_1PrivateKey.html", null ],
          [ "PublicKey", "d6/dcb/structvanetza_1_1security_1_1ecdsa256_1_1PublicKey.html", null ]
        ] ],
        [ "openssl", null, [
          [ "BigNumber", "d1/d9d/classvanetza_1_1security_1_1openssl_1_1BigNumber.html", null ],
          [ "BigNumberContext", "d3/d61/classvanetza_1_1security_1_1openssl_1_1BigNumberContext.html", null ],
          [ "Exception", "da/d93/classvanetza_1_1security_1_1openssl_1_1Exception.html", null ],
          [ "Group", "d0/dd1/classvanetza_1_1security_1_1openssl_1_1Group.html", null ],
          [ "Key", "d7/d2a/classvanetza_1_1security_1_1openssl_1_1Key.html", null ],
          [ "Point", "d2/d5b/classvanetza_1_1security_1_1openssl_1_1Point.html", null ],
          [ "Signature", "d2/def/classvanetza_1_1security_1_1openssl_1_1Signature.html", null ]
        ] ],
        [ "v2", null, [
          [ "detail", null, [
            [ "subject_attribute_type", "d7/d2e/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::Assurance_Level >", "d3/df4/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Assurance__Level_01_4.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::Encryption_Key >", "dd/db6/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Encryption__Key_01_4.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::ITS_AID_List >", "dd/d75/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1ITS__AID__List_01_4.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::ITS_AID_SSP_List >", "d6/de7/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1ITS__AID__SSP__List_01_4.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::Reconstruction_Value >", "d6/d71/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Reconstruction__Value_01_4.html", null ],
            [ "subject_attribute_type< SubjectAttributeType::Verification_Key >", "d0/d6e/structvanetza_1_1security_1_1v2_1_1detail_1_1subject__attribute__type_3_01SubjectAttributeType_1_1Verification__Key_01_4.html", null ],
            [ "validity_restriction_type", "df/d49/structvanetza_1_1security_1_1v2_1_1detail_1_1validity__restriction__type.html", null ],
            [ "validity_restriction_type< ValidityRestrictionType::Region >", "d8/db3/structvanetza_1_1security_1_1v2_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_1_1Region_01_4.html", null ],
            [ "validity_restriction_type< ValidityRestrictionType::Time_End >", "d2/de9/structvanetza_1_1security_1_1v2_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictionType_1_1Time__End_01_4.html", null ],
            [ "validity_restriction_type< ValidityRestrictionType::Time_Start_And_Duration >", "df/dab/structvanetza_1_1security_1_1v2_1_1detail_1_1validity__restriction__type_3_01ValidityRestriction666a2edd3db3d4e315f8e33c4f12d4a1.html", null ],
            [ "validity_restriction_type< ValidityRestrictionType::Time_Start_And_End >", "d1/d2a/structvanetza_1_1security_1_1v2_1_1detail_1_1validity__restriction__type_3_01ValidityRestrictiona758b9ba68831d2e09022591b8533f8d.html", null ]
          ] ],
          [ "Certificate", "dd/d19/structvanetza_1_1security_1_1v2_1_1Certificate.html", "dd/d19/structvanetza_1_1security_1_1v2_1_1Certificate" ],
          [ "CertificateCache", "d0/d52/classvanetza_1_1security_1_1v2_1_1CertificateCache.html", "d0/d52/classvanetza_1_1security_1_1v2_1_1CertificateCache" ],
          [ "CertificateDigestWithOtherAlgorithm", "d8/d04/structvanetza_1_1security_1_1v2_1_1CertificateDigestWithOtherAlgorithm.html", null ],
          [ "CertificateProvider", "dd/d76/classvanetza_1_1security_1_1v2_1_1CertificateProvider.html", "dd/d76/classvanetza_1_1security_1_1v2_1_1CertificateProvider" ],
          [ "CertificateValidator", "d0/d13/classvanetza_1_1security_1_1v2_1_1CertificateValidator.html", "d0/d13/classvanetza_1_1security_1_1v2_1_1CertificateValidator" ],
          [ "CircularRegion", "dd/d53/structvanetza_1_1security_1_1v2_1_1CircularRegion.html", null ],
          [ "DefaultCertificateValidator", "de/d37/classvanetza_1_1security_1_1v2_1_1DefaultCertificateValidator.html", "de/d37/classvanetza_1_1security_1_1v2_1_1DefaultCertificateValidator" ],
          [ "DefaultSignHeaderPolicy", "d1/dc8/classvanetza_1_1security_1_1v2_1_1DefaultSignHeaderPolicy.html", "d1/dc8/classvanetza_1_1security_1_1v2_1_1DefaultSignHeaderPolicy" ],
          [ "DeferredSignService", "d3/d37/classvanetza_1_1security_1_1v2_1_1DeferredSignService.html", null ],
          [ "DummySignService", "dd/d92/classvanetza_1_1security_1_1v2_1_1DummySignService.html", "dd/d92/classvanetza_1_1security_1_1v2_1_1DummySignService" ],
          [ "Duration", "df/d45/classvanetza_1_1security_1_1v2_1_1Duration.html", "df/d45/classvanetza_1_1security_1_1v2_1_1Duration" ],
          [ "ecdsa_nistp256_with_sha256", "da/dc8/structvanetza_1_1security_1_1v2_1_1ecdsa__nistp256__with__sha256.html", null ],
          [ "ecies_nistp256", "db/d38/structvanetza_1_1security_1_1v2_1_1ecies__nistp256.html", null ],
          [ "EciesEncryptedKey", "de/dd9/structvanetza_1_1security_1_1v2_1_1EciesEncryptedKey.html", null ],
          [ "EncryptionKey", "db/d6d/structvanetza_1_1security_1_1v2_1_1EncryptionKey.html", null ],
          [ "header_field_type", "d9/d3a/structvanetza_1_1security_1_1v2_1_1header__field__type.html", null ],
          [ "header_field_type< HeaderFieldType::Encryption_Parameters >", "da/d2b/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Encryption__Parameters_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Expiration >", "d3/d31/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Expiration_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Generation_Location >", "d0/d46/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Location_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Generation_Time >", "df/d7c/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Time_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Generation_Time_Confidence >", "d3/d48/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Time__Confidence_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Its_Aid >", "df/dea/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Its__Aid_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Recipient_Info >", "d4/df8/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Recipient__Info_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Request_Unrecognized_Certificate >", "dc/d24/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Request__Unrecognized__Certificate_01_4.html", null ],
          [ "header_field_type< HeaderFieldType::Signer_Info >", "d5/df4/structvanetza_1_1security_1_1v2_1_1header__field__type_3_01HeaderFieldType_1_1Signer__Info_01_4.html", null ],
          [ "IdentifiedRegion", "d7/d4c/structvanetza_1_1security_1_1v2_1_1IdentifiedRegion.html", null ],
          [ "IntX", "d9/d21/classvanetza_1_1security_1_1v2_1_1IntX.html", null ],
          [ "ItsAidSsp", "db/d9d/structvanetza_1_1security_1_1v2_1_1ItsAidSsp.html", null ],
          [ "NaiveCertificateProvider", "d7/dff/classvanetza_1_1security_1_1v2_1_1NaiveCertificateProvider.html", "d7/dff/classvanetza_1_1security_1_1v2_1_1NaiveCertificateProvider" ],
          [ "NoneRegion", "d0/df3/structvanetza_1_1security_1_1v2_1_1NoneRegion.html", null ],
          [ "NullCertificateProvider", "dc/d56/classvanetza_1_1security_1_1v2_1_1NullCertificateProvider.html", "dc/d56/classvanetza_1_1security_1_1v2_1_1NullCertificateProvider" ],
          [ "NullCertificateValidator", "d2/d3a/classvanetza_1_1security_1_1v2_1_1NullCertificateValidator.html", "d2/d3a/classvanetza_1_1security_1_1v2_1_1NullCertificateValidator" ],
          [ "OpaqueKey", "d8/d0d/structvanetza_1_1security_1_1v2_1_1OpaqueKey.html", null ],
          [ "Payload", "da/d87/structvanetza_1_1security_1_1v2_1_1Payload.html", null ],
          [ "RecipientInfo", "dc/d8d/structvanetza_1_1security_1_1v2_1_1RecipientInfo.html", null ],
          [ "RectangularRegion", "d7/df2/structvanetza_1_1security_1_1v2_1_1RectangularRegion.html", null ],
          [ "SecuredMessage", "d5/d43/structvanetza_1_1security_1_1v2_1_1SecuredMessage.html", "d5/d43/structvanetza_1_1security_1_1v2_1_1SecuredMessage" ],
          [ "Signature", "d1/d4d/structvanetza_1_1security_1_1v2_1_1Signature.html", null ],
          [ "SignHeaderPolicy", "d2/d2e/classvanetza_1_1security_1_1v2_1_1SignHeaderPolicy.html", "d2/d2e/classvanetza_1_1security_1_1v2_1_1SignHeaderPolicy" ],
          [ "StartAndDurationValidity", "de/db0/structvanetza_1_1security_1_1v2_1_1StartAndDurationValidity.html", null ],
          [ "StartAndEndValidity", "dd/dc5/structvanetza_1_1security_1_1v2_1_1StartAndEndValidity.html", null ],
          [ "StaticCertificateProvider", "d6/db8/classvanetza_1_1security_1_1v2_1_1StaticCertificateProvider.html", "d6/db8/classvanetza_1_1security_1_1v2_1_1StaticCertificateProvider" ],
          [ "StraightSignService", "d7/d8c/classvanetza_1_1security_1_1v2_1_1StraightSignService.html", null ],
          [ "StraightVerifyService", "d8/d4b/classvanetza_1_1security_1_1v2_1_1StraightVerifyService.html", null ],
          [ "SubjectAssurance", "d9/d04/structvanetza_1_1security_1_1v2_1_1SubjectAssurance.html", null ],
          [ "SubjectInfo", "d0/d47/structvanetza_1_1security_1_1v2_1_1SubjectInfo.html", null ],
          [ "ThreeDLocation", "da/dab/structvanetza_1_1security_1_1v2_1_1ThreeDLocation.html", null ],
          [ "Time64WithStandardDeviation", "dc/d52/structvanetza_1_1security_1_1v2_1_1Time64WithStandardDeviation.html", null ],
          [ "trailer_field_type", "d0/dc4/structvanetza_1_1security_1_1v2_1_1trailer__field__type.html", null ],
          [ "trailer_field_type< TrailerFieldType::Signature >", "d9/dc4/structvanetza_1_1security_1_1v2_1_1trailer__field__type_3_01TrailerFieldType_1_1Signature_01_4.html", null ],
          [ "TrustStore", "d7/df4/classvanetza_1_1security_1_1v2_1_1TrustStore.html", "d7/df4/classvanetza_1_1security_1_1v2_1_1TrustStore" ],
          [ "TwoDLocation", "d2/d30/structvanetza_1_1security_1_1v2_1_1TwoDLocation.html", null ],
          [ "VerificationKey", "dc/daa/structvanetza_1_1security_1_1v2_1_1VerificationKey.html", null ]
        ] ],
        [ "Backend", "d1/d75/classvanetza_1_1security_1_1Backend.html", "d1/d75/classvanetza_1_1security_1_1Backend" ],
        [ "BackendCryptoPP", "d1/ded/classvanetza_1_1security_1_1BackendCryptoPP.html", "d1/ded/classvanetza_1_1security_1_1BackendCryptoPP" ],
        [ "BackendNull", "d4/d9f/classvanetza_1_1security_1_1BackendNull.html", "d4/d9f/classvanetza_1_1security_1_1BackendNull" ],
        [ "BackendOpenSsl", "d1/dee/classvanetza_1_1security_1_1BackendOpenSsl.html", "d1/dee/classvanetza_1_1security_1_1BackendOpenSsl" ],
        [ "CamPermissions", "df/df3/classvanetza_1_1security_1_1CamPermissions.html", "df/df3/classvanetza_1_1security_1_1CamPermissions" ],
        [ "Certificate", "da/d35/structvanetza_1_1security_1_1Certificate.html", "da/d35/structvanetza_1_1security_1_1Certificate" ],
        [ "CertificateCache", "d0/d29/classvanetza_1_1security_1_1CertificateCache.html", "d0/d29/classvanetza_1_1security_1_1CertificateCache" ],
        [ "CertificateDigestWithOtherAlgorithm", "da/d22/structvanetza_1_1security_1_1CertificateDigestWithOtherAlgorithm.html", null ],
        [ "CertificateProvider", "dd/d27/classvanetza_1_1security_1_1CertificateProvider.html", "dd/d27/classvanetza_1_1security_1_1CertificateProvider" ],
        [ "CertificateValidator", "d1/d27/classvanetza_1_1security_1_1CertificateValidator.html", "d1/d27/classvanetza_1_1security_1_1CertificateValidator" ],
        [ "CertificateValidity", "dc/dbb/classvanetza_1_1security_1_1CertificateValidity.html", "dc/dbb/classvanetza_1_1security_1_1CertificateValidity" ],
        [ "CircularRegion", "da/d86/structvanetza_1_1security_1_1CircularRegion.html", null ],
        [ "Compressed_Lsb_Y_0", "dc/d84/structvanetza_1_1security_1_1Compressed__Lsb__Y__0.html", null ],
        [ "Compressed_Lsb_Y_1", "d9/d56/structvanetza_1_1security_1_1Compressed__Lsb__Y__1.html", null ],
        [ "DecapConfirm", "de/dd6/structvanetza_1_1security_1_1DecapConfirm.html", null ],
        [ "DecapRequest", "d7/df7/structvanetza_1_1security_1_1DecapRequest.html", null ],
        [ "DefaultCertificateValidator", "de/d8a/classvanetza_1_1security_1_1DefaultCertificateValidator.html", "de/d8a/classvanetza_1_1security_1_1DefaultCertificateValidator" ],
        [ "DefaultSignHeaderPolicy", "d0/de7/classvanetza_1_1security_1_1DefaultSignHeaderPolicy.html", "d0/de7/classvanetza_1_1security_1_1DefaultSignHeaderPolicy" ],
        [ "DefaultSigningPolicy", "d4/d16/classvanetza_1_1security_1_1DefaultSigningPolicy.html", null ],
        [ "DelegatingSecurityEntity", "d0/dff/classvanetza_1_1security_1_1DelegatingSecurityEntity.html", "d0/dff/classvanetza_1_1security_1_1DelegatingSecurityEntity" ],
        [ "deserialization_error", "d6/d77/classvanetza_1_1security_1_1deserialization__error.html", null ],
        [ "Duration", "dd/d77/classvanetza_1_1security_1_1Duration.html", "dd/d77/classvanetza_1_1security_1_1Duration" ],
        [ "ecdsa_nistp256_with_sha256", "d9/d39/structvanetza_1_1security_1_1ecdsa__nistp256__with__sha256.html", null ],
        [ "EcdsaSignature", "d0/dd5/structvanetza_1_1security_1_1EcdsaSignature.html", null ],
        [ "EcdsaSignatureFuture", "dd/d5d/classvanetza_1_1security_1_1EcdsaSignatureFuture.html", null ],
        [ "ecies_nistp256", "d4/d1b/structvanetza_1_1security_1_1ecies__nistp256.html", null ],
        [ "EciesEncryptedKey", "d1/de8/structvanetza_1_1security_1_1EciesEncryptedKey.html", null ],
        [ "EncapConfirm", "d6/d82/structvanetza_1_1security_1_1EncapConfirm.html", null ],
        [ "EncapRequest", "d4/d09/structvanetza_1_1security_1_1EncapRequest.html", null ],
        [ "EncryptionKey", "dd/d9d/structvanetza_1_1security_1_1EncryptionKey.html", null ],
        [ "header_field_type", "dc/dfc/structvanetza_1_1security_1_1header__field__type.html", null ],
        [ "header_field_type< HeaderFieldType::Encryption_Parameters >", "db/d25/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Encryption__Parameters_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Expiration >", "d0/d8e/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Expiration_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Generation_Location >", "d8/dd7/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Location_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Generation_Time >", "d2/d1e/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Time_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Generation_Time_Confidence >", "d9/d91/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Generation__Time__Confidence_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Its_Aid >", "d6/da5/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Its__Aid_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Recipient_Info >", "df/d61/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Recipient__Info_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Request_Unrecognized_Certificate >", "d1/dcd/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Request__Unrecognized__Certificate_01_4.html", null ],
        [ "header_field_type< HeaderFieldType::Signer_Info >", "de/d24/structvanetza_1_1security_1_1header__field__type_3_01HeaderFieldType_1_1Signer__Info_01_4.html", null ],
        [ "IdentifiedRegion", "d8/db6/structvanetza_1_1security_1_1IdentifiedRegion.html", null ],
        [ "IntX", "d2/d93/classvanetza_1_1security_1_1IntX.html", null ],
        [ "ItsAidSsp", "d0/d11/structvanetza_1_1security_1_1ItsAidSsp.html", null ],
        [ "NaiveCertificateProvider", "d5/dda/classvanetza_1_1security_1_1NaiveCertificateProvider.html", "d5/dda/classvanetza_1_1security_1_1NaiveCertificateProvider" ],
        [ "NoneRegion", "d7/de0/structvanetza_1_1security_1_1NoneRegion.html", null ],
        [ "NullCertificateProvider", "d6/d85/classvanetza_1_1security_1_1NullCertificateProvider.html", "d6/d85/classvanetza_1_1security_1_1NullCertificateProvider" ],
        [ "NullCertificateValidator", "d3/dac/classvanetza_1_1security_1_1NullCertificateValidator.html", "d3/dac/classvanetza_1_1security_1_1NullCertificateValidator" ],
        [ "OpaqueKey", "d8/d9d/structvanetza_1_1security_1_1OpaqueKey.html", null ],
        [ "Payload", "d1/deb/structvanetza_1_1security_1_1Payload.html", null ],
        [ "RecipientInfo", "d6/dcf/structvanetza_1_1security_1_1RecipientInfo.html", null ],
        [ "RectangularRegion", "da/dbf/structvanetza_1_1security_1_1RectangularRegion.html", null ],
        [ "SecuredMessageV2", "de/de7/structvanetza_1_1security_1_1SecuredMessageV2.html", "de/de7/structvanetza_1_1security_1_1SecuredMessageV2" ],
        [ "SecurityEntity", "d9/dd4/classvanetza_1_1security_1_1SecurityEntity.html", "d9/dd4/classvanetza_1_1security_1_1SecurityEntity" ],
        [ "serialization_error", "df/db4/classvanetza_1_1security_1_1serialization__error.html", null ],
        [ "SignConfirm", "d2/d89/structvanetza_1_1security_1_1SignConfirm.html", null ],
        [ "SignHeaderPolicy", "d5/dad/classvanetza_1_1security_1_1SignHeaderPolicy.html", "d5/dad/classvanetza_1_1security_1_1SignHeaderPolicy" ],
        [ "SigningPolicy", "d6/d37/classvanetza_1_1security_1_1SigningPolicy.html", null ],
        [ "SignRequest", "d0/df9/structvanetza_1_1security_1_1SignRequest.html", null ],
        [ "StartAndDurationValidity", "d6/da7/structvanetza_1_1security_1_1StartAndDurationValidity.html", null ],
        [ "StartAndEndValidity", "d0/db4/structvanetza_1_1security_1_1StartAndEndValidity.html", null ],
        [ "StaticCertificateProvider", "d1/dd6/classvanetza_1_1security_1_1StaticCertificateProvider.html", "d1/dd6/classvanetza_1_1security_1_1StaticCertificateProvider" ],
        [ "SubjectAssurance", "d1/d19/structvanetza_1_1security_1_1SubjectAssurance.html", null ],
        [ "SubjectInfo", "d7/d54/structvanetza_1_1security_1_1SubjectInfo.html", null ],
        [ "ThreeDLocation", "d3/d65/structvanetza_1_1security_1_1ThreeDLocation.html", null ],
        [ "Time64WithStandardDeviation", "dd/dd9/structvanetza_1_1security_1_1Time64WithStandardDeviation.html", null ],
        [ "trailer_field_type", "d8/d0e/structvanetza_1_1security_1_1trailer__field__type.html", null ],
        [ "trailer_field_type< TrailerFieldType::Signature >", "db/d6e/structvanetza_1_1security_1_1trailer__field__type_3_01TrailerFieldType_1_1Signature_01_4.html", null ],
        [ "TrustStore", "d0/dfe/classvanetza_1_1security_1_1TrustStore.html", "d0/dfe/classvanetza_1_1security_1_1TrustStore" ],
        [ "TwoDLocation", "db/d4c/structvanetza_1_1security_1_1TwoDLocation.html", null ],
        [ "Uncompressed", "d3/dab/structvanetza_1_1security_1_1Uncompressed.html", null ],
        [ "VerificationKey", "dc/d87/structvanetza_1_1security_1_1VerificationKey.html", null ],
        [ "VerifyConfirm", "d5/dbe/structvanetza_1_1security_1_1VerifyConfirm.html", null ],
        [ "VerifyRequest", "dc/d48/structvanetza_1_1security_1_1VerifyRequest.html", null ],
        [ "X_Coordinate_Only", "d0/d50/structvanetza_1_1security_1_1X__Coordinate__Only.html", null ]
      ] ],
      [ "BitNumber", "dd/dba/classvanetza_1_1BitNumber.html", "dd/dba/classvanetza_1_1BitNumber" ],
      [ "BufferPacket", "d7/d97/classvanetza_1_1BufferPacket.html", null ],
      [ "byte_buffer_sink", "de/d0e/classvanetza_1_1byte__buffer__sink.html", null ],
      [ "byte_buffer_source", "da/da2/classvanetza_1_1byte__buffer__source.html", null ],
      [ "byte_view_range", "db/df6/classvanetza_1_1byte__view__range.html", "db/df6/classvanetza_1_1byte__view__range" ],
      [ "ByteBufferConvertible", "d6/dc0/classvanetza_1_1ByteBufferConvertible.html", null ],
      [ "ChunkPacket", "d1/d98/classvanetza_1_1ChunkPacket.html", "d1/d98/classvanetza_1_1ChunkPacket" ],
      [ "Clock", "d4/d73/classvanetza_1_1Clock.html", "d4/d73/classvanetza_1_1Clock" ],
      [ "CohesivePacket", "d8/db4/classvanetza_1_1CohesivePacket.html", "d8/db4/classvanetza_1_1CohesivePacket" ],
      [ "ConfidentQuantity", "d2/d35/classvanetza_1_1ConfidentQuantity.html", null ],
      [ "EndianType", "d8/df8/classvanetza_1_1EndianType.html", null ],
      [ "EthernetHeader", "db/d8e/classvanetza_1_1EthernetHeader.html", null ],
      [ "Factory", "df/d2e/classvanetza_1_1Factory.html", "df/d2e/classvanetza_1_1Factory" ],
      [ "Hook", "d7/d3f/classvanetza_1_1Hook.html", "d7/d3f/classvanetza_1_1Hook" ],
      [ "HookRegistry", "dd/d5e/classvanetza_1_1HookRegistry.html", null ],
      [ "InputArchive", "d9/dea/classvanetza_1_1InputArchive.html", "d9/dea/classvanetza_1_1InputArchive" ],
      [ "IoVector", "d0/d0a/classvanetza_1_1IoVector.html", null ],
      [ "LruCache", "db/d4d/classvanetza_1_1LruCache.html", "db/d4d/classvanetza_1_1LruCache" ],
      [ "MacAddress", "db/da9/classvanetza_1_1MacAddress.html", null ],
      [ "ManualRuntime", "dc/d1a/classvanetza_1_1ManualRuntime.html", "dc/d1a/classvanetza_1_1ManualRuntime" ],
      [ "ObjectContainer", "d1/db6/classvanetza_1_1ObjectContainer.html", "d1/db6/classvanetza_1_1ObjectContainer" ],
      [ "OutputArchive", "db/d6e/classvanetza_1_1OutputArchive.html", "db/d6e/classvanetza_1_1OutputArchive" ],
      [ "PositionConfidence", "d1/d6e/structvanetza_1_1PositionConfidence.html", null ],
      [ "PositionFix", "dd/d65/structvanetza_1_1PositionFix.html", null ],
      [ "PositionProvider", "da/d15/classvanetza_1_1PositionProvider.html", "da/d15/classvanetza_1_1PositionProvider" ],
      [ "Runtime", "de/d11/classvanetza_1_1Runtime.html", "de/d11/classvanetza_1_1Runtime" ],
      [ "socket_layer_pdu", "db/d92/structvanetza_1_1socket__layer__pdu.html", null ],
      [ "socket_layers", "d0/dd7/structvanetza_1_1socket__layers.html", null ],
      [ "StoredPositionProvider", "d1/dd6/classvanetza_1_1StoredPositionProvider.html", "d1/dd6/classvanetza_1_1StoredPositionProvider" ],
      [ "UnitInterval", "d4/d40/classvanetza_1_1UnitInterval.html", null ],
      [ "Wgs84Point", "d3/d7f/structvanetza_1_1Wgs84Point.html", null ]
    ] ]
];