find_path(GEOGRAPHICLIB_INCLUDE_DIR
    NAMES GeographicLib/GeoCoords.hpp)
find_library(GEOGRAPHICLIB_LIBRARY
    NAMES Geographic)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GeographicLib DEFAULT_MSG
    GEOGRAPHICLIB_LIBRARY GEOGRAPHICLIB_INCLUDE_DIR)

set(GEOGRAPHICLIB_INCLUDE_DIRS ${GEOGRAPHICLIB_INCLUDE_DIR})
set(GEOGRAPHICLIB_LIBRARIES ${GEOGRAPHICLIB_LIBRARY})

mark_as_advanced(GEOGRAPHICLIB_INCLUDE_DIR)
mark_as_advanced(GEOGRAPHICLIB_LIBRARY)
