set(COHDA_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/../cohda/mk2/ieee1609" CACHE FILEPATH "Cohda MK2 include dir")
set(COHDA_KERNEL_INCLUDE_DIR ${COHDA_INCLUDE_DIR}/kernel/include)
set(COHDA_LIB1609_INCLUDE_DIR ${COHDA_INCLUDE_DIR}/app/lib1609/include)
set(COHDA_INCLUDE_DIRS ${COHDA_KERNEL_INCLUDE_DIR} ${COHDA_LIB1609_INCLUDE_DIR})
