macro(asn1c_sources VAR DIR)
    file(GLOB _sources ${DIR}/*.c)
    list(REMOVE_ITEM _sources ${DIR}/converter-sample.c)
    if(NOT _sources)
        message(FATAL_ERROR "Generate sources from ASN.1 specification in ${DIR} using asn1c at first!")
    endif()
    set(${VAR} ${_sources})
endmacro()
